-- ============================================================
-- K-Movement Optimism — Migration 003b
-- 운동처방 + 신경가동술 10개
-- 생성일: 2026-04-25
-- 실행: https://supabase.com/dashboard/project/gnusyjnviugpofvaicbv/sql
-- ============================================================
-- ⚠️  실행 순서 필수:
--     1단계: 003a-exercise-enum.sql 먼저 실행 (ENUM 확장 커밋)
--     2단계: 003-exercise-setup.sql 실행 (카테고리 + 태그 INSERT)
--     3단계: 이 파일 실행 (테크닉 10개 INSERT)
-- ============================================================

-- ============================================================
-- 01. McKenzie MDT (요추)
-- ============================================================
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  category_id,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '맥켄지 기계적 진단 및 치료 (요추)',
  'McKenzie Mechanical Diagnosis and Therapy — Lumbar Spine',
  'MDT',
  'category_exercise01',
  (SELECT id FROM technique_categories WHERE category_key = 'category_exercise01'),
  'McKenzie MDT — Directional Preference',
  'lumbar',
  'L1-S1',
  false,
  '방향성 선호(Directional Preference)를 평가하여 증상이 중앙으로 모이는 집중화 현상(Centralization Phenomenon)을 유도하는 치료 시스템. 환자 스스로 반복 운동을 처방받아 자가관리하는 생물심리사회적 접근법.',
  '[
    {"step":1,"instruction":"굴곡, 신전, 측방 이동 방향별 반복 운동 검사 시행. 각 방향 10회 반복 후 증상 반응(집중화 또는 말초화) 관찰"},
    {"step":2,"instruction":"집중화 현상이 유도되는 방향을 방향성 선호로 결정. 주로 신전 선호(엎드려 팔굽혀펴기 변형)가 많음"},
    {"step":3,"instruction":"방향성 선호 방향으로 반복 운동 처방. 신전 선호 시: 복와위(엎드린 자세) 팔굽혀펴기 변형(Prone Press-Up) 10회/세트, 1~2시간마다 반복"},
    {"step":4,"instruction":"집중화 확인 후 하중 추가 순서로 진행: 복와위 → 선 자세 신전 → 체중 부하 반복 운동. 가정 운동으로 전환"},
    {"step":5,"instruction":"세션마다 집중화 유지 여부 확인. 말초화(증상 확산) 발생 시 즉시 방향 전환 또는 강도 조절. 자가 처방 교육으로 독립 유도"}
  ]'::jsonb,
  '복와위(엎드린 자세) 또는 앉은 자세',
  '환자 옆에 서서 관찰 위치 유지. 필요 시 요추 분절에 과압 적용',
  '관찰 위주, 필요 시 요추 분절 과압 적용',
  '방향성 선호에 따라 결정 (주로 신전 방향)',
  ARRAY['pain_relief','rom_improvement'],
  ARRAY['acute','subacute','chronic'],
  ARRAY['movement_pain','radiculopathy','lbp_nonspecific','disc_herniation','centralization_phenomenon'],
  ARRAY['fracture','instability','malignancy','neurological_deficit'],
  'level_1a',
  '[
    {"pmid":"30376550","title":"McKenzie method of Mechanical Diagnosis and Therapy for low back pain","year":2018,"journal":"Cochrane Database Syst Rev"},
    {"pmid":"29726357","title":"Namnaqani et al. — McKenzie Method for LBP systematic review","year":2018,"journal":"JOSPT"}
  ]'::jsonb,
  '1. 집중화 현상은 MDT 핵심 예측 지표 — 첫 평가에서 집중화 유도되면 예후 양호\n2. 환자 자가관리 능력 훈련이 목표 — 재발 시 스스로 처방 가능하도록 교육\n3. 빈도(1~2시간마다)가 세트 수보다 중요 — 하루 총 6~10세트 이행이 핵심',
  '골절(의심 포함), 척추 불안정성, 악성 종양, 진행성 신경학적 결손(마미증후군 의심 포함)',
  '골다공증, 급성 염증',
  true,
  false
)
ON CONFLICT (abbreviation) WHERE abbreviation IS NOT NULL DO UPDATE SET
  name_ko            = EXCLUDED.name_ko,
  name_en            = EXCLUDED.name_en,
  category           = EXCLUDED.category,
  category_id        = EXCLUDED.category_id,
  body_region        = EXCLUDED.body_region,
  technique_steps    = EXCLUDED.technique_steps,
  purpose_tags       = EXCLUDED.purpose_tags,
  target_tags        = EXCLUDED.target_tags,
  symptom_tags       = EXCLUDED.symptom_tags,
  contraindication_tags = EXCLUDED.contraindication_tags,
  evidence_level     = EXCLUDED.evidence_level,
  key_references     = EXCLUDED.key_references,
  clinical_notes     = EXCLUDED.clinical_notes,
  absolute_contraindications = EXCLUDED.absolute_contraindications,
  relative_contraindications = EXCLUDED.relative_contraindications,
  updated_at         = NOW();

-- ============================================================
-- 02. Motor Control Exercise (MCE)
-- ============================================================
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  category_id,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '신경운동 조절 운동 (심부 코어 재활성화)',
  'Motor Control Exercise',
  'MCE',
  'category_exercise01',
  (SELECT id FROM technique_categories WHERE category_key = 'category_exercise01'),
  'Deep Stabilizer Reactivation',
  'lumbar',
  'L4-L5, L5-S1',
  false,
  '요통 환자에서 억제되는 심부 안정화 근육(복횡근, 다열근)의 신경운동 조절을 재활성화하는 훈련. 의식적 활성화에서 점차 자동적·기능적 통합으로 진행.',
  '[
    {"step":1,"instruction":"압력 바이오피드백 유닛(PBU)을 요추 아래 설치, 기준값 70mmHg. 복횡근 단독 수축 시 압력 변화 관찰 (2~4mmHg 감소가 정상)"},
    {"step":2,"instruction":"복부 드로-인(Abdominal Draw-In): 천장 호흡(코로 들이쉬고 입으로 내쉬기) 유지하면서 배꼽 아래를 척추 방향으로 살짝 당기기. 발살바(숨 참기) 없이 10초 유지"},
    {"step":3,"instruction":"요추 분절 수준 다열근 등척성 수축: 치료사 촉진 피드백과 함께 분절 다열근 수축 유도. 10초 유지 × 10회"},
    {"step":4,"instruction":"심부 근육 활성화 상태에서 사지 움직임 추가: 버드독(Bird Dog), 데드버그(Dead Bug) 순서로 진행"},
    {"step":5,"instruction":"서기·걷기·직업 동작에서 심부 근육 활성화 유지 여부 확인. 매 4~6주마다 PBU 재평가 실시"}
  ]'::jsonb,
  '누운 자세(훅 라잉: 무릎 굽힌 앙와위) 또는 네발기기 자세',
  '환자 옆, 요추 및 복부 촉진 위치',
  '하복부(복횡근 촉진), 요추 다열근 분절 촉진',
  '해당 없음 (근수축 활성화 훈련)',
  ARRAY['pain_relief','stabilization','proprioception'],
  ARRAY['subacute','chronic','post_surgical'],
  ARRAY['movement_pain','lbp_nonspecific','recurrent_lbp','movement_control_deficit'],
  ARRAY['fracture','instability','malignancy','neurological_deficit'],
  'level_1a',
  '[
    {"pmid":"26415751","title":"Effectiveness of motor control exercises versus general exercises for chronic LBP","year":2016,"journal":"JOSPT"},
    {"pmid":"7894835","title":"Hodges PW — Inefficient muscular stabilization of the lumbar spine","year":1996,"journal":"Spine"}
  ]'::jsonb,
  '1. 강도보다 선택성이 우선 — 복직근(표층) 대신 복횡근(심부) 선택적 활성화\n2. 움직임 조절 결함이 확인된 환자에게 가장 효과적\n3. 수술 후 재활에서 복횡근 선행 활성화(Feedforward) 패턴 회복이 핵심 목표',
  '골절, 척추 불안정성, 악성 종양, 신경학적 결손',
  '골다공증, 급성 염증기',
  true,
  false
)
ON CONFLICT (abbreviation) WHERE abbreviation IS NOT NULL DO UPDATE SET
  name_ko            = EXCLUDED.name_ko,
  name_en            = EXCLUDED.name_en,
  category           = EXCLUDED.category,
  category_id        = EXCLUDED.category_id,
  body_region        = EXCLUDED.body_region,
  technique_steps    = EXCLUDED.technique_steps,
  purpose_tags       = EXCLUDED.purpose_tags,
  target_tags        = EXCLUDED.target_tags,
  symptom_tags       = EXCLUDED.symptom_tags,
  contraindication_tags = EXCLUDED.contraindication_tags,
  evidence_level     = EXCLUDED.evidence_level,
  key_references     = EXCLUDED.key_references,
  clinical_notes     = EXCLUDED.clinical_notes,
  absolute_contraindications = EXCLUDED.absolute_contraindications,
  relative_contraindications = EXCLUDED.relative_contraindications,
  updated_at         = NOW();

-- ============================================================
-- 03. Core Stability Training (McGill Big 3)
-- ============================================================
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  category_id,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '코어 안정화 훈련 (맥길 빅 쓰리)',
  'Core Stability Training — McGill Big 3',
  'McGill Big 3',
  'category_exercise01',
  (SELECT id FROM technique_categories WHERE category_key = 'category_exercise01'),
  'McGill Core Endurance Protocol',
  'lumbar',
  '전반적 요추·흉요추 이행부',
  false,
  '로컬(심부) 근육군과 글로벌(표층) 근육군을 통합적으로 강화하여 척추의 역동적 안정성을 향상. McGill Big 3(버드독, 수정 컬업, 사이드 플랭크) 기반 내구성 훈련.',
  '[
    {"step":1,"instruction":"자세 평가 + 요추 중립 자세(Neutral Spine) 교육. 통증 유발 동작 확인 후 범위 조절"},
    {"step":2,"instruction":"버드독(Bird Dog): 네발기기 자세에서 반대팔-다리 동시 신전. 요추 회전 없이 중립 유지. 8~10회/측, 2~3세트"},
    {"step":3,"instruction":"수정 컬업(Modified Curl-Up): 무릎 굽힌 누운 자세, 한 손을 요추 아래에 대고 상부 흉추만 살짝 들기. 경추 중립 유지. 5→3→1 하강 피라미드, 각 8~10초 홀드"},
    {"step":4,"instruction":"사이드 플랭크(Side Plank): 무릎 구부린 자세부터 시작 → 발 지지 자세로 진행. 엉덩이 들림 유지 10~30초. 3세트/측"},
    {"step":5,"instruction":"데드버그, 플랭크 추가 후 스쿼트·힌지 등 기능 동작으로 이행. 매 4주 전체 재평가"}
  ]'::jsonb,
  '매트 위 누운 자세 또는 네발기기 자세',
  '관찰 및 교정 위치. 필요 시 요추 중립 자세 확인 위해 손을 요추 아래에 위치',
  '필요 시 요추 아래에 손 위치 (중립 확인)',
  '해당 없음',
  ARRAY['pain_relief','rom_improvement','stabilization'],
  ARRAY['subacute','chronic','post_surgical'],
  ARRAY['movement_pain','lbp_nonspecific','recurrent_lbp','sport_return'],
  ARRAY['fracture','instability','malignancy','neurological_deficit'],
  'level_1a',
  '[
    {"pmid":"35475753","title":"Network meta-analysis of exercise for chronic low back pain","year":2022,"journal":"JOSPT"}
  ]'::jsonb,
  '1. 횟수보다 "정확한 조절과 느린 속도"가 우선 — 잘못된 자세 100회보다 바른 자세 10회\n2. McGill Big 3는 척추 부하를 최소화하면서 안정화를 훈련하도록 설계 — 반드시 이 3개를 기본으로\n3. 급성기 통증 일부 조절 후(NPRS ≤ 5) 시작',
  '골절, 척추 불안정성, 악성 종양, 신경학적 결손',
  '골다공증, 급성 염증기',
  true,
  false
)
ON CONFLICT (abbreviation) WHERE abbreviation IS NOT NULL DO UPDATE SET
  name_ko            = EXCLUDED.name_ko,
  name_en            = EXCLUDED.name_en,
  category           = EXCLUDED.category,
  category_id        = EXCLUDED.category_id,
  body_region        = EXCLUDED.body_region,
  technique_steps    = EXCLUDED.technique_steps,
  purpose_tags       = EXCLUDED.purpose_tags,
  target_tags        = EXCLUDED.target_tags,
  symptom_tags       = EXCLUDED.symptom_tags,
  contraindication_tags = EXCLUDED.contraindication_tags,
  evidence_level     = EXCLUDED.evidence_level,
  key_references     = EXCLUDED.key_references,
  clinical_notes     = EXCLUDED.clinical_notes,
  absolute_contraindications = EXCLUDED.absolute_contraindications,
  relative_contraindications = EXCLUDED.relative_contraindications,
  updated_at         = NOW();

-- ============================================================
-- 04. Graded Activity
-- ============================================================
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  category_id,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '점진적 활동 (행동주의적 재활)',
  'Graded Activity',
  'GA',
  'category_exercise01',
  (SELECT id FROM technique_categories WHERE category_key = 'category_exercise01'),
  'Quota-Based Behavioral Rehabilitation',
  'lumbar',
  NULL,
  false,
  '통증 신호가 아닌 기능 목표(Quota System)를 기반으로 활동량을 점진적으로 증가시키는 행동주의적 접근. 두려움-회피 행동을 개선하고 생물심리사회적 모델로 만성 요통을 관리.',
  '[
    {"step":1,"instruction":"FABQ(두려움-회피 믿음 설문), TSK(Tampa Scale of Kinesiophobia) 평가. 환자와 함께 구체적 기능 목표 설정(걷기 10분, 계단 오르기, 직장 복귀 등). 현재 가능한 활동 수준(베이스라인) 측정"},
    {"step":2,"instruction":"통증 한계점 이하에서 시작 활동량 결정. 시간 기반(Time-Contingent) 원칙: 통증 유무와 상관없이 미리 정한 할당량에 따라 진행"},
    {"step":3,"instruction":"세션마다 활동량 5~10% 증가. 통증이 있어도 할당량 달성 시 긍정적 강화. 페이싱(Pacing) 전략 교육: 좋은 날 과하게 하고 나쁜 날 아무것도 안 하는 패턴 예방"},
    {"step":4,"instruction":"매 세션 통증 신경과학 교육 5~10분 병합. 통증=위협 신호이지 손상 신호가 아님을 반복 교육"},
    {"step":5,"instruction":"설정한 기능 목표 달성률 평가. 자가 관리 전략 교육 후 독립적 유지 계획 수립"}
  ]'::jsonb,
  '앉은 자세 (초기 면담), 이후 활동 종류에 따라 다양',
  '면담·코칭 위치',
  '해당 없음 (행동주의적 접근)',
  '해당 없음',
  ARRAY['pain_relief','rom_improvement'],
  ARRAY['chronic'],
  ARRAY['movement_pain','rest_pain','fear_avoidance','kinesiophobia','chronic_lbp','disability_high'],
  ARRAY['fracture','instability','malignancy','neurological_deficit'],
  'level_1b',
  '[
    {"pmid":"39748454","title":"Graded Activity vs usual care for chronic LBP","year":2025,"journal":"PMC"},
    {"pmid":"20395628","title":"Graded Activity versus Graded Exposure for LBP","year":2010,"journal":"JOSPT"}
  ]'::jsonb,
  '1. KMO 핵심 철학 "Calm things down, Build things back up"과 가장 직결 — 기능 회복이 통증 소멸보다 먼저\n2. 황색 깃발(두려움-회피, 파국화)이 다수인 만성 요통에서 가장 강력한 선택\n3. PNE와 병합할 때 효과 배가 — 단독 사용보다 운동+인지행동치료 요소 통합 권장',
  '골절, 척추 불안정성, 악성 종양, 신경학적 결손',
  '주요 우울증 동반 시 심리치료사 협진 필요',
  true,
  false
)
ON CONFLICT (abbreviation) WHERE abbreviation IS NOT NULL DO UPDATE SET
  name_ko            = EXCLUDED.name_ko,
  name_en            = EXCLUDED.name_en,
  category           = EXCLUDED.category,
  category_id        = EXCLUDED.category_id,
  body_region        = EXCLUDED.body_region,
  technique_steps    = EXCLUDED.technique_steps,
  purpose_tags       = EXCLUDED.purpose_tags,
  target_tags        = EXCLUDED.target_tags,
  symptom_tags       = EXCLUDED.symptom_tags,
  contraindication_tags = EXCLUDED.contraindication_tags,
  evidence_level     = EXCLUDED.evidence_level,
  key_references     = EXCLUDED.key_references,
  clinical_notes     = EXCLUDED.clinical_notes,
  absolute_contraindications = EXCLUDED.absolute_contraindications,
  relative_contraindications = EXCLUDED.relative_contraindications,
  updated_at         = NOW();

-- ============================================================
-- 05. Neurodynamic Mobilization
-- ============================================================
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  category_id,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '신경 가동술 (좌골신경 적용)',
  'Neurodynamic Mobilization — Sciatic Nerve',
  'NM',
  'category_d_neural',
  (SELECT id FROM technique_categories WHERE category_key = 'category_d_neural'),
  'Neural Slider & Tensioner',
  'lumbar',
  'L4-L5, L5-S1',
  false,
  '신경조직의 기계적·생리적 기능을 회복하기 위해 신경을 미끄러트리거나(Slider) 당기는(Tensioner) 기법. 좌골신경 관련 방사통, 신경 긴장 소견 있는 요통 환자에 적용.',
  '[
    {"step":1,"instruction":"SLR(Straight Leg Raise) 검사: 70° 미만에서 방사통 재현 시 양성. Slump 검사: 앉아서 경추 굴곡+슬관절 신전 조합으로 신경 긴장 확인. 신경 긴장 유발 위치·방향 파악"},
    {"step":2,"instruction":"Slider 기법 우선 적용. 앙와위 SLR Slider: 고관절 굴곡(슬관절 신전)과 경추 굴곡을 동시에 → 경추 신전하면서 고관절 낮추기(두 끝을 반대 방향으로 교대). 리드미컬하게 15회/세트"},
    {"step":3,"instruction":"Slump Slider 적용: 앉은 자세 경추 굴곡+슬관절 신전을 반대 방향으로 교대. 양쪽 동시 또는 편측 적용. 15회 × 2세트"},
    {"step":4,"instruction":"통증 내성에 따라 고관절 굴곡 범위 점진 증가. Slider → Tensioner 순서로 증상 개선 후 단계 전환"},
    {"step":5,"instruction":"가정 운동 처방: 누운 자세 또는 앉은 자세 SLR Slider, 일 2회. 매 세션 SLR 범위 재평가로 효과 추적"}
  ]'::jsonb,
  '누운 자세(앙와위) — SLR Slider / 앉은 자세 — Slump Slider',
  '환자 발 쪽, 고관절·슬관절 지지 위치',
  '발뒤꿈치(뒤꿈치 컵 그립) + 슬관절 후면 지지',
  '고관절 굴곡 방향, 경추 굴곡 방향 (Slider: 반대로 교대)',
  ARRAY['pain_relief','rom_improvement','neurodynamics'],
  ARRAY['acute','subacute','chronic'],
  ARRAY['movement_pain','radiculopathy','sciatic_pain','neural_tension','disc_herniation'],
  ARRAY['fracture','instability','malignancy','neurological_deficit'],
  'level_1a',
  '[
    {"pmid":"28704591","title":"Neural mobilization for lumbar and lower limb conditions: systematic review","year":2017,"journal":"JOSPT"},
    {"pmid":"38138623","title":"Neural mobilization for lumbar radiculopathy: meta-analysis","year":2023,"journal":"PMC"}
  ]'::jsonb,
  '1. 신경을 "스트레칭"이 아닌 "미끄러뜨리는" 개념 — Slider가 Tensioner보다 신경계 부담 적어 우선 적용\n2. SLR 범위 개선이 치료 효과의 객관적 지표 — 매 세션 측정\n3. 날카로운 통증 유발 시 즉시 범위 축소 — 약한 당기는 느낌은 정상',
  '골절, 척추 불안정성, 악성 종양, 진행성 신경학적 결손(마미증후군 의심 포함), 척수 압박',
  '급성 신경근 염증기(Tensioner 금기, Slider만 조심스럽게 적용)',
  true,
  false
)
ON CONFLICT (abbreviation) WHERE abbreviation IS NOT NULL DO UPDATE SET
  name_ko            = EXCLUDED.name_ko,
  name_en            = EXCLUDED.name_en,
  category           = EXCLUDED.category,
  category_id        = EXCLUDED.category_id,
  body_region        = EXCLUDED.body_region,
  technique_steps    = EXCLUDED.technique_steps,
  purpose_tags       = EXCLUDED.purpose_tags,
  target_tags        = EXCLUDED.target_tags,
  symptom_tags       = EXCLUDED.symptom_tags,
  contraindication_tags = EXCLUDED.contraindication_tags,
  evidence_level     = EXCLUDED.evidence_level,
  key_references     = EXCLUDED.key_references,
  clinical_notes     = EXCLUDED.clinical_notes,
  absolute_contraindications = EXCLUDED.absolute_contraindications,
  relative_contraindications = EXCLUDED.relative_contraindications,
  updated_at         = NOW();

-- ============================================================
-- 06. Deep Cervical Flexor Training
-- ============================================================
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  category_id,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '심부 경추 굴곡근 훈련',
  'Deep Cervical Flexor Training',
  'DCFT',
  'category_exercise01',
  (SELECT id FROM technique_categories WHERE category_key = 'category_exercise01'),
  'Cranio-Cervical Flexion Training',
  'cervical',
  'C1-C4',
  false,
  '경추통에서 약화되는 심부 경추 굴곡근(두장근, 경장근)을 선택적으로 재활성화. CCFT(두개경추 굴곡 검사)를 평가 도구로 사용하여 표층 굴곡근의 과활성화 패턴을 억제하고 심부 근육 우선 활성화 패턴 재훈련.',
  '[
    {"step":1,"instruction":"CCFT 평가: PBU를 목 뒤에 설치, 기준값 20mmHg. 22, 24, 26, 28, 30mmHg 순서로 5단계 고개 끄덕임 각도 조절. 각 단계 10초 유지 가능 여부 + 표층근(흉쇄유돌근) 과활성 여부 촉진 확인"},
    {"step":2,"instruction":"현재 가능한 mmHg 단계에서 시작. 흉쇄유돌근에 손가락 대고 과활성 없는지 자가 모니터링 지도. 10초 유지 × 10회 × 2~3세트"},
    {"step":3,"instruction":"10초 × 10회 달성 시 다음 단계(+2mmHg) 상향. 표층근 활성화 없이 목표 단계 유지가 단계 전환 기준"},
    {"step":4,"instruction":"앉은 자세 → 선 자세 → 동적 자세 순서로 DCF 활성화 유지 훈련. 경추 후퇴(Retraction) 동작과 통합"},
    {"step":5,"instruction":"PBU 없이 감각 피드백만으로 고개 끄덕임 훈련 지도. 일 3회, 주 5일 가정 훈련 처방"}
  ]'::jsonb,
  '누운 자세(앙와위), 목 뒤에 PBU 설치',
  '환자 옆, 흉쇄유돌근·전사각근 촉진 위치',
  '경부 표층 근육(흉쇄유돌근) 촉진 — 과활성 여부 모니터링',
  '두개경추 굴곡 방향 (고개 끄덕임)',
  ARRAY['pain_relief','stabilization','proprioception'],
  ARRAY['subacute','chronic'],
  ARRAY['movement_pain','cervicogenic_ha','neck_pain_chronic','whiplash','forward_head_posture'],
  ARRAY['vbi_risk','fracture','instability','malignancy','neurological_deficit'],
  'level_1b',
  '[
    {"pmid":"18804003","title":"Jull et al. — Clinical assessment of CCFT: validity and reliability","year":2008,"journal":"Physical Therapy"},
    {"pmid":"25603175","title":"DCF training with pressure biofeedback unit for neck pain","year":2015,"journal":"PMC"},
    {"pmid":"36516745","title":"Exercise therapy for neck pain: systematic review and meta-analysis","year":2023,"journal":"JOSPT"}
  ]'::jsonb,
  '1. CCFT 목표 단계를 벗어나지 않는 것이 핵심 — 너무 강하면 표층근이 보상 수축\n2. 표층근(흉쇄유돌근)이 활성화되지 않는 범위에서만 훈련 — 심부근 선택성이 핵심\n3. 경추성 두통 환자에서 DCF 훈련이 두통 빈도·강도 모두에 유의한 개선 효과',
  '척추동맥 혈액순환 장애 위험(VBI), 골절, 척추 불안정성, 악성 종양, 신경학적 결손',
  '골다공증, 급성 염증',
  true,
  false
)
ON CONFLICT (abbreviation) WHERE abbreviation IS NOT NULL DO UPDATE SET
  name_ko            = EXCLUDED.name_ko,
  name_en            = EXCLUDED.name_en,
  category           = EXCLUDED.category,
  category_id        = EXCLUDED.category_id,
  body_region        = EXCLUDED.body_region,
  technique_steps    = EXCLUDED.technique_steps,
  purpose_tags       = EXCLUDED.purpose_tags,
  target_tags        = EXCLUDED.target_tags,
  symptom_tags       = EXCLUDED.symptom_tags,
  contraindication_tags = EXCLUDED.contraindication_tags,
  evidence_level     = EXCLUDED.evidence_level,
  key_references     = EXCLUDED.key_references,
  clinical_notes     = EXCLUDED.clinical_notes,
  absolute_contraindications = EXCLUDED.absolute_contraindications,
  relative_contraindications = EXCLUDED.relative_contraindications,
  updated_at         = NOW();

-- ============================================================
-- 07. Cervical McKenzie
-- ============================================================
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  category_id,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '경추 맥켄지 (후퇴+신전 시퀀스)',
  'Cervical McKenzie — Retraction & Extension Sequence',
  'Cervical MDT',
  'category_exercise01',
  (SELECT id FROM technique_categories WHERE category_key = 'category_exercise01'),
  'McKenzie MDT — Cervical Directional Preference',
  'cervical',
  'C3-C7',
  false,
  '경추에 MDT 원칙을 적용. 후퇴(Retraction)가 경추의 1차 처방 운동이며, 필요 시 신전(Extension) 추가. 집중화 현상 유도가 핵심 치료 목표.',
  '[
    {"step":1,"instruction":"반복 후퇴(Repeated Retraction) 10회, 필요 시 반복 신전 추가. 집중화(팔/손 증상이 목으로 이동) 또는 말초화 여부 확인. 방향성 선호 결정: 후퇴/후퇴+신전/굴곡/측방 이동 중 선택"},
    {"step":2,"instruction":"앉거나 선 자세에서 턱을 수평으로 뒤로 당기기(이중턱 만들기). 끝 범위에서 1~2초 유지 후 중립 복귀. 10~15회/세트"},
    {"step":3,"instruction":"집중화 미발생 시 신전 추가: 후퇴 끝에서 고개를 뒤로 젖히기. 치료사 과압 적용: 양손으로 후두부 지지 후 신전 방향으로 부드럽게 과압"},
    {"step":4,"instruction":"팔꿈치 아래 증상: 매 1시간마다 반복 / 팔꿈치 위 증상: 2~3시간마다 반복. 증상 소멸 후 3일 무증상까지 지속, 이후 빈도 점감"},
    {"step":5,"instruction":"앉은 자세 경추 중립 교육, 베개 높이 조정. 재발 시 스스로 처방 가능하도록 자가 처방 훈련"}
  ]'::jsonb,
  '앉은 자세 또는 선 자세',
  '환자 옆·뒤, 과압(Overpressure) 적용 위치',
  '후두부 또는 하악 (과압 적용 시)',
  '수평 후방(후퇴) → 필요 시 신전 추가',
  ARRAY['pain_relief','rom_improvement'],
  ARRAY['acute','subacute','chronic'],
  ARRAY['movement_pain','radiculopathy','cervical_derangement','neck_pain','centralization_phenomenon'],
  ARRAY['vbi_risk','fracture','instability','malignancy','neurological_deficit'],
  'level_1b',
  '[
    {"pmid":"38625050","title":"MDT vs wait-and-see for cervical radiculopathy — 6-week RCT","year":2024,"journal":"JOSPT Open"},
    {"pmid":"18369546","title":"McKenzie MDT for cervical radiculopathy: case series","year":2008,"journal":"PMC"}
  ]'::jsonb,
  '1. 집중화 현상 확인이 예후 예측 핵심 지표 — 요추 MDT와 동일 원칙\n2. 경추 신전 시 VBI 스크리닝 필수 선행 — 특히 고령·혈관 질환 위험인자 보유자\n3. 후퇴 동작은 "이중턱 만들기"로 설명하면 환자 수행 정확도가 높아짐',
  '척추동맥 혈액순환 장애 위험(VBI), 골절, 척추 불안정성, 악성 종양, 척수증(Myelopathy) 의심',
  '골다공증, 급성 염증',
  true,
  false
)
ON CONFLICT (abbreviation) WHERE abbreviation IS NOT NULL DO UPDATE SET
  name_ko            = EXCLUDED.name_ko,
  name_en            = EXCLUDED.name_en,
  category           = EXCLUDED.category,
  category_id        = EXCLUDED.category_id,
  body_region        = EXCLUDED.body_region,
  technique_steps    = EXCLUDED.technique_steps,
  purpose_tags       = EXCLUDED.purpose_tags,
  target_tags        = EXCLUDED.target_tags,
  symptom_tags       = EXCLUDED.symptom_tags,
  contraindication_tags = EXCLUDED.contraindication_tags,
  evidence_level     = EXCLUDED.evidence_level,
  key_references     = EXCLUDED.key_references,
  clinical_notes     = EXCLUDED.clinical_notes,
  absolute_contraindications = EXCLUDED.absolute_contraindications,
  relative_contraindications = EXCLUDED.relative_contraindications,
  updated_at         = NOW();

-- ============================================================
-- 08. Proprioceptive Retraining
-- ============================================================
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  category_id,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '경추 고유감각 재훈련',
  'Cervical Proprioceptive Retraining',
  'CPR',
  'category_exercise01',
  (SELECT id FROM technique_categories WHERE category_key = 'category_exercise01'),
  'Laser Pointer Head Repositioning Training',
  'cervical',
  'C0-C2',
  false,
  '경추통 환자·편타손상 후 환자에서 손상되는 두부 위치 감각(Head Repositioning Accuracy)과 경추 관절 고유감각을 재훈련. 레이저 포인터 헤드밴드를 이용한 움직임 추적 훈련이 대표 기법.',
  '[
    {"step":1,"instruction":"JPE(Joint Position Error Test) 시행: 눈 감고 목표 방향(30° 회전, 25° 굴·신전) 복귀 정확도 측정. 정상 기준 오차 < 4.5°. 오차 > 4.5° = 고유감각 재훈련 적응증 확인"},
    {"step":2,"instruction":"레이저 포인터 훈련(눈 뜨고): 헤드밴드에 레이저 포인터 장착. 벽의 목표 지점(십자, 원, 숫자) 추적. 8자, 원, 직선 패턴 순서로 10~15분 훈련"},
    {"step":3,"instruction":"눈 감고 난이도 증가: 동일 패턴을 눈 감고 수행. 목표 지점 기억 후 정확히 레이저 위치시키는 훈련. 위치 도달 후 눈 뜨고 오차 확인"},
    {"step":4,"instruction":"자세 난이도 증가: 앉기 → 서기 → 폼 패드 위 서기(불안정면) 순서. 안구 운동+경추 움직임 협응 훈련(Gaze Stabilization) 추가"},
    {"step":5,"instruction":"거울 앞에서 레이저 없이 감각 피드백으로 수행 지도. 4주마다 JPE 재측정으로 효과 객관화"}
  ]'::jsonb,
  '앉은 자세 (표준), 이후 선 자세 → 불안정면 순서로 진행',
  '환자 옆, 안전 확보 위치 (낙상 방지)',
  '필요 시 어깨 지지 (낙상 방지)',
  '해당 없음 (감각운동 훈련)',
  ARRAY['pain_relief','rom_improvement','proprioception'],
  ARRAY['subacute','chronic'],
  ARRAY['movement_pain','dizziness_cervicogenic','cervicogenic_ha','whiplash','balance_disorder','neck_pain_chronic'],
  ARRAY['vbi_risk','fracture','instability','malignancy','neurological_deficit'],
  'level_1b',
  '[
    {"pmid":"38722247","title":"Home-based proprioceptive training for neck pain: RCT","year":2024,"journal":"PLOS ONE"},
    {"pmid":"38290215","title":"Exercise for cervical proprioception improvement: systematic review","year":2024,"journal":"PMC"}
  ]'::jsonb,
  '1. 편타손상(Whiplash) 후 고유감각 결손이 만성화 핵심 기전 — 조기 평가·훈련이 예후에 중요\n2. BPPV(이석증)와 경추성 어지럼증 감별이 선행되어야 훈련 효과 극대화\n3. 눈 감고 훈련 비중이 고유감각 강화의 핵심 — 눈 뜨고는 피드백 확인 용도',
  '척추동맥 혈액순환 장애 위험(VBI), 골절, 척추 불안정성, 악성 종양, 신경학적 결손',
  'BPPV(이석증) 의심 시 이석 정복(Epley) 먼저 시행',
  true,
  false
)
ON CONFLICT (abbreviation) WHERE abbreviation IS NOT NULL DO UPDATE SET
  name_ko            = EXCLUDED.name_ko,
  name_en            = EXCLUDED.name_en,
  category           = EXCLUDED.category,
  category_id        = EXCLUDED.category_id,
  body_region        = EXCLUDED.body_region,
  technique_steps    = EXCLUDED.technique_steps,
  purpose_tags       = EXCLUDED.purpose_tags,
  target_tags        = EXCLUDED.target_tags,
  symptom_tags       = EXCLUDED.symptom_tags,
  contraindication_tags = EXCLUDED.contraindication_tags,
  evidence_level     = EXCLUDED.evidence_level,
  key_references     = EXCLUDED.key_references,
  clinical_notes     = EXCLUDED.clinical_notes,
  absolute_contraindications = EXCLUDED.absolute_contraindications,
  relative_contraindications = EXCLUDED.relative_contraindications,
  updated_at         = NOW();

-- ============================================================
-- 09. Cervical Strengthening
-- ============================================================
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  category_id,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '경추 주변근 강화 훈련',
  'Cervical Strengthening Exercise',
  'CSE',
  'category_exercise01',
  (SELECT id FROM technique_categories WHERE category_key = 'category_exercise01'),
  'Progressive Cervical Resistance Training',
  'cervical',
  'C1-C7',
  false,
  '경추 굴곡근·신전근·회전근의 등척성 → 등심성 → 저항 순서로 단계별 강화. 심부 근육(DCF 훈련)과 병행하여 표층 근육 강도·내구성을 향상.',
  '[
    {"step":1,"instruction":"등척성 훈련(통증 억제 단계): 굴곡-이마에 손 대고 밀어붙이기(목 움직이지 않음) 10초 유지. 신전-양손 깍지 끼고 뒤통수 밀기. 측굴·회전 방향 동일 적용. 5~10회 × 10초 유지"},
    {"step":2,"instruction":"등심성 훈련: 저항 없이 가동 범위 전체에서 조절된 운동. 고개 숙임→중립 복귀(굴곡), 고개 뒤로→중립 복귀(신전). 느린 속도, 통증 없는 전 범위"},
    {"step":3,"instruction":"저항 훈련: 저항 밴드 또는 기계 저항 사용. 점진적 과부하 원칙: 2주마다 저항 증가. 3세트 × 10~15회"},
    {"step":4,"instruction":"DCF 훈련 병합: DCF 활성화 확인 후 표층 근육 강화. 순서: DCF 활성화 → 등척성 → 등심성 → 저항 단계 통합"},
    {"step":5,"instruction":"기능 통합 + 재평가: 컴퓨터 작업·운전 등 직업 동작에서 경추 근력 유지 훈련. 6주마다 경추 근력 검사로 재평가"}
  ]'::jsonb,
  '앉은 자세 (등척성 단계) / 다양한 자세 (등심성·저항 단계)',
  '환자 앞 또는 옆, 저항 제공 위치',
  '이마(굴곡 저항), 후두부(신전 저항), 측두부(측굴 저항)',
  '굴곡, 신전, 측굴, 회전 4방향',
  ARRAY['pain_relief','rom_improvement','stabilization'],
  ARRAY['subacute','chronic'],
  ARRAY['movement_pain','radiculopathy','cervical_spondylosis','neck_pain_chronic','cervicogenic_ha','occupational_neck_pain'],
  ARRAY['vbi_risk','fracture','instability','malignancy','neurological_deficit'],
  'level_1b',
  '[
    {"pmid":"35449282","title":"Isometric cervical exercise for cervical spondylosis: RCT","year":2022,"journal":"BMC Sports Science"},
    {"pmid":"36001369","title":"Effects of cervical exercise protocol on NDI, NPRS, ROM","year":2022,"journal":"PMC"}
  ]'::jsonb,
  '1. 등척성 6회/일 × 6일/주 × 4주 프로토콜이 경추 척추증 RCT에서 유의한 개선 — 빈도가 강도보다 중요\n2. DCF 훈련(심부) 병행 필수 — 심부근 안정화 + 표층근 강화의 층위 이해\n3. 직업성 경추통(컴퓨터 작업, 고개 숙임 작업)에서 강화 훈련이 가장 효과적인 1차 선택',
  '척추동맥 혈액순환 장애 위험(VBI), 골절, 척추 불안정성, 악성 종양, 척수증 의심',
  '골다공증, 급성 염증',
  true,
  false
)
ON CONFLICT (abbreviation) WHERE abbreviation IS NOT NULL DO UPDATE SET
  name_ko            = EXCLUDED.name_ko,
  name_en            = EXCLUDED.name_en,
  category           = EXCLUDED.category,
  category_id        = EXCLUDED.category_id,
  body_region        = EXCLUDED.body_region,
  technique_steps    = EXCLUDED.technique_steps,
  purpose_tags       = EXCLUDED.purpose_tags,
  target_tags        = EXCLUDED.target_tags,
  symptom_tags       = EXCLUDED.symptom_tags,
  contraindication_tags = EXCLUDED.contraindication_tags,
  evidence_level     = EXCLUDED.evidence_level,
  key_references     = EXCLUDED.key_references,
  clinical_notes     = EXCLUDED.clinical_notes,
  absolute_contraindications = EXCLUDED.absolute_contraindications,
  relative_contraindications = EXCLUDED.relative_contraindications,
  updated_at         = NOW();

-- ============================================================
-- 10. Pain Neuroscience Education (PNE)
-- ============================================================
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  category_id,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '통증 신경과학 교육 병합 접근',
  'Pain Neuroscience Education — Combined Approach',
  'PNE',
  'category_exercise01',
  (SELECT id FROM technique_categories WHERE category_key = 'category_exercise01'),
  'Reconceptualization & Behavioral Integration',
  'cervical',
  NULL,
  false,
  '통증을 "손상 신호"가 아닌 "위협 신호"로 재개념화(Reconceptualization)하는 교육. 중추감작화(Central Sensitization)가 관여하는 만성 경추통·요통에서 운동치료와 병합 시 가장 효과적.',
  '[
    {"step":1,"instruction":"PCS(통증 파국화 척도), SOPA(통증에 대한 인식 설문) 시행. 개방형 질문: 통증 원인에 대한 환자의 믿음 확인. 파국화, 통제 불능감, 과잉 의료 탐색 패턴 파악"},
    {"step":2,"instruction":"신경과학 기반 교육: 알람 시스템 비유, 볼륨 조절 비유 활용. 시각 자료(뉴런 그림, 신경계 다이어그램) 제공. 강의 형식 지양 — 대화형, 질문-답변 방식. 15~30분/세션"},
    {"step":3,"instruction":"재프레이밍 연습: ''통증 = 손상''이 아닌 ''통증 = 위협 신호'' 개념 반복 확인. 이전 부적응적 믿음을 환자 스스로 교정하도록 유도"},
    {"step":4,"instruction":"운동치료·도수치료와 통합: 매 세션 운동 전후 짧은 PNE 복습 5~10분. Graded Activity 또는 Graded Exposure와 병합"},
    {"step":5,"instruction":"효과 재평가: PCS 재측정(임상적으로 의미 있는 변화 ≥ 9.1점 감소), TSK 재측정. 운동 처방 순응도 변화 추적"}
  ]'::jsonb,
  '앉은 자세 (면담 및 교육)',
  '환자 맞은편 — 동등한 대화 위치',
  '해당 없음 (언어·시각 교육 중심)',
  '해당 없음',
  ARRAY['pain_relief'],
  ARRAY['chronic'],
  ARRAY['movement_pain','rest_pain','central_sensitization','pain_catastrophizing','neck_pain_chronic','chronic_lbp','fear_avoidance'],
  ARRAY['fracture','instability','malignancy','neurological_deficit'],
  'level_1a',
  '[
    {"pmid":"33418440","title":"PNE revisited: what do we know","year":2021,"journal":"JOSPT"},
    {"pmid":"39808369","title":"PNE meta-analysis for chronic low back pain","year":2025,"journal":"MDPI"},
    {"pmid":"28166593","title":"Multimodal pain treatment protocol for spinal pain","year":2017,"journal":"PMC"}
  ]'::jsonb,
  '1. "통증은 실제입니다 — 다만 조직 손상의 크기를 정확히 반영하지 않습니다"가 핵심 메시지\n2. PNE는 보조 개입으로 가장 효과적 — 운동치료+도수치료와 통합할 때 시너지\n3. 파국화 점수(PCS > 30) 높은 환자에서 PNE 선행 시 이후 운동 순응도 현저히 향상',
  '골절, 척추 불안정성, 악성 종양, 신경학적 결손',
  '주요 정신질환(우울증, PTSD, 조현병) 동반 시 심리치료사 협진 선행',
  true,
  false
)
ON CONFLICT (abbreviation) WHERE abbreviation IS NOT NULL DO UPDATE SET
  name_ko            = EXCLUDED.name_ko,
  name_en            = EXCLUDED.name_en,
  category           = EXCLUDED.category,
  category_id        = EXCLUDED.category_id,
  body_region        = EXCLUDED.body_region,
  technique_steps    = EXCLUDED.technique_steps,
  purpose_tags       = EXCLUDED.purpose_tags,
  target_tags        = EXCLUDED.target_tags,
  symptom_tags       = EXCLUDED.symptom_tags,
  contraindication_tags = EXCLUDED.contraindication_tags,
  evidence_level     = EXCLUDED.evidence_level,
  key_references     = EXCLUDED.key_references,
  clinical_notes     = EXCLUDED.clinical_notes,
  absolute_contraindications = EXCLUDED.absolute_contraindications,
  relative_contraindications = EXCLUDED.relative_contraindications,
  updated_at         = NOW();

-- ============================================================
-- End of seed: 10 techniques inserted (9 category_exercise01 + 1 category_d_neural)
-- ============================================================
