-- ============================================================
-- KMO 도수치료 테크닉 Seed Data
-- 원본: seed_techniques.json
-- 생성일: 2026-04-24T12:33:36.602Z
-- 총 42개 테크닉
-- 대상 테이블: techniques (schema.sql 기준)
-- 주의: id 컬럼은 uuid_generate_v4() 자동 생성
-- ============================================================

-- 기존 데이터 초기화 (technique_stats 등 cascade 포함)
TRUNCATE TABLE techniques RESTART IDENTITY CASCADE;

-- [1/42] 경추 중앙 PA 가동술 (tech-A-001)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '경추 중앙 PA 가동술',
  'Cervical Central Posteroanterior Mobilization',
  'Cx CPA',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'cervical'::body_region,
  'C2–C7 극돌기',
  false,
  '복와위 환자의 경추 극돌기에 양 엄지로 후방→전방 방향으로 리드미컬한 진동을 가하는 Maitland 관절가동술. Grade I·II는 통증 조절, Grade III·IV는 ROM 회복 목적으로 사용.',
  '[{"step":1,"instruction":"환자를 복와위로 눕히고 이마는 치료대 헤드피스에 편안히 위치시킨다. 팔은 몸 옆, 흉부 하방에 얇은 베개로 경추 자연 굴곡 유지."},{"step":2,"instruction":"목표 척추 극돌기(C2–C7)를 촉진하여 정확한 접촉점을 설정한다."},{"step":3,"instruction":"양 엄지 끝(pad)을 극돌기에 부드럽게 접촉. 나머지 손가락은 경추 양측에 자연스럽게 얹어 지지."},{"step":4,"instruction":"치료사 상체 체중을 앞으로 이동시켜 PA 방향(약 10–15° 두측 경사)으로 압력 적용. 손목·손가락 힘 아닌 체중 이동 사용."},{"step":5,"instruction":"Grade별 진폭 조절: Grade I(소진폭, R1 이전, 2–3Hz, 10–25N) / Grade II(대진폭, R1 미도달, 2Hz, 25–50N) / Grade III(대진폭, R1 통과, 50–80N) / Grade IV(소진폭, R2 근처, 60–92N)."},{"step":6,"instruction":"1세트 30–60회 또는 60초 적용. 시술 중 방사통·현기증 등 비정상 반응 지속 모니터링."}]'::jsonb,
  '복와위(prone), 이마 헤드피스에 위치, 팔 몸 옆, 흉부 하 얇은 베개',
  '환자 머리 방향에 위치, 양발 어깨 너비, 체중 앞뒤 이동 준비',
  '양 엄지 끝(pad)을 목표 극돌기에 접촉, 엄지 끝 나란히 또는 맞닿음',
  '후방→전방(PA), 약 10–15° 두측(cranial) 방향 경사',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic"}',
  '{"lbp_nonspecific","cervicogenic_ha","radiculopathy"}',
  '{"instability","malignancy","fracture","vbi_risk"}',
  'level_1b'::evidence_level,
  '[{"pmid":"8281150","title":"Maitland cervical mobilization for neck pain: RCT","year":2022},{"pmid":"5361027","title":"Cervical PA mobilization effects on NDI and ROM","year":2017}]'::jsonb,
  'irritability 먼저 평가: 야간통·안정 시 통증 있으면 Grade I·II부터 시작. C3–C6 가장 빈번. 한국 임상에서 손목 힘만 쓰는 오류 흔함 — 반드시 체중 이동 사용. Grade III/IV는 경추 NDI 개선·ROM 증가에 유의한 효과.',
  '경추 불안정(AAI, 류마티스), 척추 종양, 급성 골절·탈구, VBI 의심',
  '급성 고자극성 신경근증, 심한 골다공증',
  true,
  false
);

-- [2/42] 경추 단측 PA 가동술 (tech-A-002)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '경추 단측 PA 가동술',
  'Cervical Unilateral PA Mobilization',
  'Cx UPA',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'cervical'::body_region,
  'C1–C7 관절돌기(articular pillar)',
  false,
  '경추 추간관절(facet joint)에 단측으로 PA 압력을 가하는 Maitland 가동술. 극돌기 외측 1–1.5cm의 관절돌기에 접촉하여 편측성 경통, 편측 두통, 방사통에 우선 적용.',
  '[{"step":1,"instruction":"환자를 복와위로 눕히고 증상 방향에 따라 머리를 소량(5–10°) 회전 허용. 어깨 이완."},{"step":2,"instruction":"목표 레벨 관절돌기(articular pillar)를 촉진: 극돌기 외측 1–1.5cm 위치."},{"step":3,"instruction":"이동손(mobilizing hand) 엄지 끝을 관절돌기에 접촉. 고정손으로 반대편 경추 지지."},{"step":4,"instruction":"PA 방향으로 15–20° 내측(medial) + 두측(cranial) 벡터로 압력 적용. 체중 이동 활용."},{"step":5,"instruction":"Grade I–IV 적용. Grade I·II: 급성·고자극성. Grade III·IV: 만성·ROM 제한."},{"step":6,"instruction":"30–60초 또는 30–60회/세트. 증상 악화·방사통 확인."}]'::jsonb,
  '복와위, 머리 헤드피스, 증상 측 5–10° 회전 허용',
  '환자 머리 측방, 목표 레벨 동측에 서서 작업',
  '엄지 끝을 관절돌기(극돌기 외측 1–1.5cm)에 접촉',
  'PA 방향, 15–20° 내측(medial) + 두측(cranial) 벡터',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic"}',
  '{"cervicogenic_ha","radiculopathy"}',
  '{"instability","malignancy","fracture","vbi_risk"}',
  'level_1b'::evidence_level,
  '[{"pmid":"8281150","title":"Maitland cervical mobilization: RCT","year":2022}]'::jsonb,
  '편측성 증상에 CPA보다 우선. 증상 재현 허용(NRS 4/10 이하). 방사통 악화 즉시 중단. C1–C2는 특수 훈련 후 시행 권장.',
  '경추 불안정, 척추 종양, 급성 골절·탈구, VBI 의심',
  '급성 고자극성 신경근증',
  true,
  false
);

-- [3/42] 흉추 중앙 PA 가동술 (tech-A-003)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '흉추 중앙 PA 가동술',
  'Thoracic Central PA Mobilization',
  'Tx CPA',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'thoracic'::body_region,
  'T1–T12 극돌기',
  false,
  '복와위에서 흉추 극돌기에 양손 엄지 또는 두상골(pisiform)로 PA 방향 진동을 가하는 Maitland 가동술. 흉추 강직, 흉통, 경부·견갑 연관통에 적용.',
  '[{"step":1,"instruction":"환자 복와위, 팔은 몸 옆 또는 치료대 양측. 흉추 자연 후만이 유지되도록 복부 하 얇은 베개 선택적 사용."},{"step":2,"instruction":"목표 흉추 극돌기 촉진. T1–T4는 경추에서 하방 촉진, T7–T12는 하위 늑골 기준으로 확인."},{"step":3,"instruction":"양 엄지 끝을 극돌기에 접촉(상위 흉추) 또는 두상골/pisiform을 극돌기에 접촉(하위 흉추·더 큰 힘 필요 시)."},{"step":4,"instruction":"PA 방향으로 약간 두측 경사로 진동 적용. 체중 이동으로 힘 전달."},{"step":5,"instruction":"Grade I–IV 적용: Grade I·II(급성·고자극성), Grade III·IV(만성·강직)."},{"step":6,"instruction":"30–60회/세트, 1–3세트. 호흡 주기에 맞춰 날숨 시 압력 증가 가능."}]'::jsonb,
  '복와위, 팔 몸 옆, 복부 하 얇은 베개 선택적 사용',
  '환자 옆에 서서 목표 레벨 정면에 위치',
  '양 엄지 끝 또는 두상골(pisiform)을 극돌기에 접촉',
  '후방→전방(PA), 약간 두측 경사',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic"}',
  '{"lbp_nonspecific","cervicogenic_ha"}',
  '{"osteoporosis","malignancy","fracture"}',
  'level_1b'::evidence_level,
  '[{"pmid":"22169956","title":"Thoracic manipulation and mobilization for neck pain: systematic review","year":2012}]'::jsonb,
  '날숨 시 압력 증가 기법으로 더 깊은 Grade 적용 가능. 골다공증 환자에서 늑골 골절 위험 — 힘 과도 금지. 흉추 가동술은 경부통·견갑통에도 간접 효과.',
  '척추 종양, 급성 골절, 심한 골다공증',
  '골다공증, 늑골 이상, 흉부 수술 후',
  true,
  false
);

-- [4/42] 흉추 단측 PA 가동술 (tech-A-004)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '흉추 단측 PA 가동술',
  'Thoracic Unilateral PA Mobilization',
  'Tx UPA',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'thoracic'::body_region,
  'T1–T12 추간관절(zygapophyseal joint)',
  false,
  '흉추 추간관절 또는 늑척추관절(costovertebral joint)에 단측으로 PA 압력을 가하는 Maitland 가동술. 편측 흉통, 늑간통, 편측 경부·견갑 방사통에 적용.',
  '[{"step":1,"instruction":"환자 복와위. 목표 레벨 확인."},{"step":2,"instruction":"극돌기 외측 2–3cm(흉추 관절돌기 위치) 촉진."},{"step":3,"instruction":"엄지 끝 또는 두상골을 관절돌기 또는 늑척추관절에 접촉."},{"step":4,"instruction":"PA 방향으로 약간 내측 + 두측 벡터로 압력 적용."},{"step":5,"instruction":"Grade I–IV 적용. 날숨 시 적용 권장."},{"step":6,"instruction":"30–60회/세트. 늑간 방사통 악화 시 즉시 중단."}]'::jsonb,
  '복와위, 팔 몸 옆',
  '환자 증상 측에 서서 목표 레벨 정면에 위치',
  '엄지 끝 또는 두상골을 관절돌기(극돌기 외측 2–3cm) 또는 늑척추관절에 접촉',
  'PA 방향, 약간 내측(medial) + 두측(cranial)',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic"}',
  '{"lbp_nonspecific"}',
  '{"osteoporosis","malignancy","fracture"}',
  'level_2b'::evidence_level,
  '[{"pmid":"22169956","title":"Thoracic manipulation and mobilization for neck pain","year":2012}]'::jsonb,
  '늑척추관절(costovertebral joint)에 적용 시 늑간신경통 감별 필요. 편측 흉통 원인이 내장기 연관통일 수 있으므로 감별 진단 선행.',
  '척추 종양, 급성 골절, 심한 골다공증',
  '골다공증, 늑골 이상',
  true,
  false
);

-- [5/42] 요추 중앙 PA 가동술 (tech-A-005)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '요추 중앙 PA 가동술',
  'Lumbar Central PA Mobilization',
  'L CPA',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'lumbar'::body_region,
  'L1–L5 극돌기',
  false,
  '복와위에서 요추 극돌기에 두상골(pisiform) 또는 양 엄지로 PA 방향 진동을 가하는 Maitland 가동술. 비특이적 요통, 요추 강직, 요추 관절 기원 통증에 가장 빈용되는 기법.',
  '[{"step":1,"instruction":"환자 복와위, 팔은 몸 옆, 복부 하 얇은 베개(요추 전만 완화용) 선택적 사용."},{"step":2,"instruction":"목표 요추 극돌기 촉진(L1–L5). L4–L5는 장골능 기준으로 확인."},{"step":3,"instruction":"두상골(pisiform) 또는 양 엄지 끝을 극돌기에 접촉. 큰 힘이 필요한 Grade III·IV는 두상골 사용 권장."},{"step":4,"instruction":"PA 방향으로 수직에 가깝게(약간 두측 경사) 압력 적용. 체중 이동 활용."},{"step":5,"instruction":"Grade별 압력: Grade I(20–30N), Grade II(30–50N), Grade III(50–80N), Grade IV(60–100N). 2Hz 진동."},{"step":6,"instruction":"30–60회/세트, 1–3세트. 하지 방사통 악화 즉시 중단."}]'::jsonb,
  '복와위, 팔 몸 옆, 복부 하 얇은 베개 선택적 사용',
  '환자 옆에 서서 양팔 뻗은 자세, 체중 이동 가능하도록 발 어깨 너비',
  '두상골(pisiform) 또는 양 엄지 끝을 극돌기에 접촉',
  '후방→전방(PA), 약간 두측 경사, 수직에 가까운 방향',
  '{"pain_relief","rom_improvement"}',
  '{"acute","subacute","chronic"}',
  '{"lbp_nonspecific","disc_herniation"}',
  '{"malignancy","fracture","instability"}',
  'level_1a'::evidence_level,
  '[{"pmid":"24139539","title":"Spinal manipulative therapy for acute low-back pain: Cochrane review","year":2012},{"pmid":"32093832","title":"Manual therapy for nonspecific low back pain: meta-analysis","year":2020}]'::jsonb,
  '요추 PA 가동술은 비특이적 요통에 가장 근거가 충분한 기법. Grade I·II부터 시작하여 환자 반응 확인 후 Grade 상향. 하지 방사통이 있는 경우 말초화(peripheralization) 주의.',
  '마미총증후군(cauda equina syndrome), 척추 종양, 급성 골절·탈구',
  '급성 추간판 탈출증, 척추 불안정, 골다공증',
  true,
  false
);

-- [6/42] 요추 단측 PA 및 회전 가동술 (tech-A-006)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '요추 단측 PA 및 회전 가동술',
  'Lumbar Unilateral PA and Rotation Mobilization',
  'L UPA+Rot',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'lumbar'::body_region,
  'L1–L5 추간관절(facet joint)',
  false,
  '요추 추간관절에 단측으로 PA 압력을 가하거나 회전 방향 가동술을 결합하는 Maitland 기법. 편측 요통, 편측 요추 추간관절 증후군, 방사통 동반 요통에 적용.',
  '[{"step":1,"instruction":"환자 복와위. 목표 요추 추간관절(극돌기 외측 약 2cm) 촉진."},{"step":2,"instruction":"엄지 끝 또는 두상골을 관절돌기에 접촉."},{"step":3,"instruction":"PA 방향 + 약간 내측(medial) 벡터로 압력 적용(UPA)."},{"step":4,"instruction":"회전 요소 추가 시: 환자 측와위로 변경, 요추 회전 가동술(Lumbar Rotation Mobilization) 병행."},{"step":5,"instruction":"Grade I–IV 적용. 편측 방사통 시 증상 방향 확인 후 방향 조정."},{"step":6,"instruction":"30–60회/세트. 증상 말초화 시 즉시 중단."}]'::jsonb,
  '복와위(UPA) 또는 측와위(회전 요소 추가 시)',
  '환자 증상 측에 위치',
  '엄지 끝 또는 두상골을 관절돌기(극돌기 외측 2cm)에 접촉',
  'PA 방향 + 내측(medial), 또는 회전 방향',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic"}',
  '{"lbp_nonspecific","radiculopathy"}',
  '{"malignancy","fracture","instability"}',
  'level_1b'::evidence_level,
  '[{"pmid":"32093832","title":"Manual therapy for nonspecific low back pain: meta-analysis","year":2020}]'::jsonb,
  '편측 증상에 CPA보다 우선 고려. 방사통 말초화 즉시 중단. 회전 요소는 만성 편측 요통에 효과적.',
  '마미총증후군, 척추 종양, 급성 골절',
  '급성 추간판 탈출증, 척추 불안정',
  true,
  false
);

-- [7/42] 천장관절 PA 가동술 (tech-A-007)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '천장관절 PA 가동술',
  'Sacroiliac Joint PA Mobilization',
  'SIJ PA',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'sacroiliac'::body_region,
  '천장관절(SI joint), 천골 후면',
  false,
  '복와위에서 천골 또는 장골에 PA 방향 압력을 가하는 Maitland 가동술. 천장관절 기원 요통, 엉덩이 통증, 임신 관련 골반대 통증에 적용.',
  '[{"step":1,"instruction":"환자 복와위. 복부 하 베개로 골반 전방경사 완화."},{"step":2,"instruction":"천골 후면 또는 목표 장골 후상장골극(PSIS) 촉진."},{"step":3,"instruction":"두상골 또는 손 전체를 천골/PSIS에 접촉."},{"step":4,"instruction":"PA 방향(수직)으로 압력 적용. 천골 측은 양손 포개서 더 큰 힘 가능."},{"step":5,"instruction":"Grade I–IV 적용. Grade I·II 먼저 적용하여 반응 확인."},{"step":6,"instruction":"30–60회/세트. 하지 방사통 변화 모니터링."}]'::jsonb,
  '복와위, 복부 하 베개 선택적 사용',
  '환자 옆, 목표 관절 정면에 위치',
  '두상골 또는 손 전체를 천골 후면 또는 PSIS에 접촉',
  '후방→전방(PA), 수직 방향',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic"}',
  '{"lbp_nonspecific"}',
  '{"malignancy","fracture","instability"}',
  'level_2b'::evidence_level,
  '[{"pmid":"17428705","title":"Manual therapy for sacroiliac joint dysfunction: a systematic review","year":2007}]'::jsonb,
  'SIJ 통증 진단은 Provocation test(FABER, Thigh Thrust 등) 클러스터로 확인 후 시행. 임신 중 골반대 통증에는 조심스럽게 Grade I·II만 적용.',
  '골반 골절, 척추 종양, 심한 불안정성',
  '임신 후기, 천장관절 융합',
  true,
  false
);

-- [8/42] 견관절 후방 활주 (Kaltenborn) (tech-A-008)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '견관절 후방 활주 (Kaltenborn)',
  'Glenohumeral Posterior Glide (Kaltenborn)',
  'GH Post Glide',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'shoulder'::body_region,
  '상완골두(humeral head) — 관절와(glenoid)',
  false,
  'Kaltenborn 기법으로 상완골두를 후방으로 활주시켜 GH 관절 내회전·수평내전 ROM을 회복하는 sustained glide 기법. 동결견, 회전근개 증후군에 주로 적용.',
  '[{"step":1,"instruction":"환자 앙와위 또는 측와위. 어깨를 휴지 위치(resting position): 약 55° 외전, 약간 수평내전, 중립 회전."},{"step":2,"instruction":"한 손으로 근위 상완골을 파지(mobilizing hand). 반대 손으로 견갑골 안정화(stabilizing hand)."},{"step":3,"instruction":"후방 방향으로 슬랙을 제거(Grade 1: 슬랙 제거 전, Grade 2: 슬랙 제거·조직 긴장, Grade 3: 최대 신장)."},{"step":4,"instruction":"Grade 2(치료적 sustained glide): 30초 유지 × 15세트(총 10분 프로토콜)."},{"step":5,"instruction":"Grade 3: 관절 가동 범위 끝까지 신장. 통증 없이 저항감만 느껴지는 지점까지."},{"step":6,"instruction":"치료 후 내회전·수평내전 ROM 재평가."}]'::jsonb,
  '앙와위 또는 측와위, 어깨 휴지 위치(약 55° 외전)',
  '환자 측방, 상완골 근위부를 파지하고 견갑골 안정화',
  'mobilizing hand: 근위 상완골 전면. stabilizing hand: 견갑골 후면',
  '후방(posterior) 활주',
  '{"rom_improvement","pain_relief"}',
  '{"subacute","chronic"}',
  '{"frozen_shoulder","rotator_cuff"}',
  '{"instability","fracture","inflammation_acute"}',
  'level_1b'::evidence_level,
  '[{"pmid":"18227433","title":"Glenohumeral joint mobilization for stiffness: systematic review","year":2008}]'::jsonb,
  'Kaltenborn Grade 2: 슬랙 제거 + 조직 긴장(치료적 범위). Grade 3: 최대 신장. 동결견 Grade 3: 30초 × 15세트(10분 총 프로토콜) 근거 있음. 내회전 ROM 제한이 주증상일 때 우선 선택.',
  '견관절 불안정, 급성 골절, 급성 염증',
  '회전근개 파열(전층), 최근 어깨 수술',
  true,
  false
);

-- [9/42] 견관절 견인 (Kaltenborn) (tech-A-009)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '견관절 견인 (Kaltenborn)',
  'Glenohumeral Distraction (Kaltenborn)',
  'GH Distraction',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'shoulder'::body_region,
  '상완골두(humeral head) — 관절와(glenoid)',
  false,
  'Kaltenborn 기법으로 상완골두를 관절와에서 수직으로 견인하여 관절낭 신장 및 통증 감소를 목표로 하는 sustained traction 기법.',
  '[{"step":1,"instruction":"환자 앙와위, 어깨 휴지 위치(약 55° 외전, 약간 전방 굴곡, 중립 회전)."},{"step":2,"instruction":"한 손으로 원위 상완골 파지(치료사 몸에 고정). 반대 손으로 액와(axilla) 근위 상완골 지지."},{"step":3,"instruction":"관절면에 수직 방향으로 슬랙 제거(Grade 1)."},{"step":4,"instruction":"Grade 2: 조직 긴장이 느껴지는 지점까지 견인 유지 10–30초."},{"step":5,"instruction":"Grade 3: 최대 신장, 10–30초 유지. 통증 없이 긴장감만 허용."},{"step":6,"instruction":"치료 후 어깨 ROM 전 방향 재평가."}]'::jsonb,
  '앙와위, 어깨 휴지 위치(약 55° 외전, 약간 전방 굴곡)',
  '환자 측방, 원위 상완골 고정 + 액와 지지',
  '원위 상완골(근위 전완 근처) + 액와 근위 상완골',
  '관절면 수직(distraction) 방향',
  '{"pain_relief","rom_improvement"}',
  '{"acute","subacute","chronic"}',
  '{"frozen_shoulder","rotator_cuff"}',
  '{"instability","fracture","inflammation_acute"}',
  'level_2b'::evidence_level,
  '[{"pmid":"18227433","title":"Glenohumeral joint mobilization for stiffness","year":2008}]'::jsonb,
  'Grade 1 견인은 통증 조절 목적. Grade 2·3은 관절낭 신장. 열 치료(습열) 후 적용 시 효과 증대. 급성 동결견에 Grade 1 견인으로 통증 관리 가능.',
  '견관절 불안정, 급성 골절',
  '회전근개 전층 파열, 급성 염증기',
  true,
  false
);

-- [10/42] 요골두 후방 활주 (tech-A-010)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '요골두 후방 활주',
  'Radial Head Posterior Glide',
  'RH Post Glide',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'elbow'::body_region,
  '근위 요척관절(proximal radioulnar joint) / 상완요골관절',
  false,
  '요골두(radial head)를 후방으로 활주시켜 전완 회전 ROM 및 팔꿈치 굴곡 ROM을 회복하는 Maitland 기법. 외측상과통증·전완 회전 제한에 적용.',
  '[{"step":1,"instruction":"환자 앉거나 앙와위. 팔꿈치 70° 굴곡, 전완 중립 또는 약간 회내."},{"step":2,"instruction":"고정손으로 상완골 내측을 감싸 고정. 이동손 엄지를 요골두 후면에, 손가락을 전면에서 감싸 접촉."},{"step":3,"instruction":"요골두를 후방(dorsal/posterior) 방향으로 활주 적용."},{"step":4,"instruction":"Grade II: 저항 이전 부드러운 활주, 60초. Grade III: 저항 속 대진폭. Grade IV: 저항 끝 소진폭."},{"step":5,"instruction":"전완 회전(회내·회외) ROM 재평가."}]'::jsonb,
  '앉거나 앙와위, 팔꿈치 70° 굴곡, 전완 중립',
  '환자 팔 측방, 상완골 내측 고정 + 요골두 접촉',
  '이동손 엄지를 요골두 후면에, 손가락을 전면에서 감싸 파지',
  '배측(dorsal/posterior) 활주',
  '{"rom_improvement","pain_relief"}',
  '{"subacute","chronic","post_surgical"}',
  '{"lateral_epicondylalgia"}',
  '{"fracture","instability"}',
  'level_2b'::evidence_level,
  '[{"pmid":"25269557","title":"Elbow joint mobilization for lateral epicondylalgia","year":2014}]'::jsonb,
  '외측상과통증에서 요골두 후방 활주는 통증 감소 및 파악력 개선에 효과적. Mulligan Tennis Elbow MWM과 병행 권장. 요골두 과거 골절력 있으면 X-ray 확인 후 진행.',
  '요골두 골절, 급성 탈구',
  '팔꿈치 수술 후 초기',
  true,
  false
);

-- [11/42] 팔꿈치 전방 활주 가동술 (굴곡 개선) (tech-A-011)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '팔꿈치 전방 활주 가동술 (굴곡 개선)',
  'Humeroulnar Anterior Glide Mobilization',
  'HU Ant Glide',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'elbow'::body_region,
  '상완척골관절(humeroulnar joint)',
  false,
  '척골을 전방(anterior)으로 활주시켜 팔꿈치 굴곡 ROM을 회복하는 Maitland 기법. 골절·수술 후 팔꿈치 굴곡 제한에 적용.',
  '[{"step":1,"instruction":"환자 앙와위. 팔꿈치 굴곡 제한 각도 약 10° 이전에서 포지션 설정. 전완 중립 또는 약간 회외."},{"step":2,"instruction":"고정손으로 원위 상완골 내측·외측을 감싸 고정."},{"step":3,"instruction":"이동손으로 요척골 근위부(anconeus 부위) 배측을 손바닥으로 감싸 접촉."},{"step":4,"instruction":"전완을 전방(anterior) + 약간 원위(distal) 방향으로 활주. Grade별 진폭 조절."},{"step":5,"instruction":"Grade III·IV 시 굴곡 방향 압력과 연계 가능. 치료 후 굴곡 ROM 재평가."}]'::jsonb,
  '앙와위, 팔꿈치 굴곡 제한 각도 근처, 전완 중립',
  '환자 팔 측방, 상완골 고정 + 전완 근위부 파지',
  '이동손: 요척골 근위부(anconeus 부위) 배측. 고정손: 원위 상완골 내·외측',
  '전방(anterior) + 약간 원위(distal) 방향 활주',
  '{"rom_improvement"}',
  '{"post_surgical","chronic","subacute"}',
  '{}',
  '{"instability","fracture"}',
  'level_2b'::evidence_level,
  '[{"pmid":"25269557","title":"Elbow joint mobilization for ROM recovery","year":2014}]'::jsonb,
  '수술 후 팔꿈치 강직 환자에서 가동술 + CPM 병행 효과적. 접촉 전 정중신경·척골신경 위치 확인 필수.',
  '내측 측부인대 불안정, 급성 골절',
  '팔꿈치 수술 후 초기(6주 이내)',
  true,
  false
);

-- [12/42] 요수근 관절 후방 활주 가동술 (tech-A-012)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '요수근 관절 후방 활주 가동술',
  'Radiocarpal Posterior Glide Mobilization',
  'RC Post Glide',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'wrist_hand'::body_region,
  '요수근 관절(radiocarpal joint)',
  false,
  '수근골을 후방(dorsal)으로 활주시켜 손목 굴곡 ROM을 회복하는 Maitland 기법. Concave-convex rule: 요수근관절은 요골(오목)이 수근골(볼록)을 받으므로 굴곡 개선 시 후방 활주 적용.',
  '[{"step":1,"instruction":"환자 앉거나 앙와위. 팔꿈치 90° 굴곡, 전완 중립. 전완을 치료대에 지지, 손목은 치료대 끝 밖으로."},{"step":2,"instruction":"고정손으로 요골·척골 원위부(styloid 근위)를 잡아 고정."},{"step":3,"instruction":"이동손 엄지+손가락으로 근위 수근골(주상골·월상골) 배측면을 잡기."},{"step":4,"instruction":"수근골을 후방(dorsal) 방향으로 활주. Grade II: 저항 이전 30–60초. Grade III: 저항 속 대진폭. Grade IV: 저항 끝 소진폭."},{"step":5,"instruction":"치료 후 손목 굴곡 ROM 재평가."}]'::jsonb,
  '앉거나 앙와위, 전완 치료대 지지, 손목 치료대 끝 밖으로',
  '환자 전방 또는 측방',
  '고정손: 요골·척골 원위부. 이동손: 근위 수근골 배측면',
  '후방(dorsal/posterior) 활주',
  '{"rom_improvement","pain_relief"}',
  '{"post_surgical","chronic","subacute"}',
  '{}',
  '{"fracture","instability"}',
  'level_2b'::evidence_level,
  '[{"pmid":"23347869","title":"Hand therapy joint mobilization for ROM: systematic review","year":2013}]'::jsonb,
  '원위 요골 골절 후 재활에서 가장 빈번히 필요한 기법. 카르팔터널 증상 악화 시 즉시 중단(정중신경 압박).',
  '급성 골절, 요수근 불안정',
  '카르팔터널 증후군 심한 경우',
  true,
  false
);

-- [13/42] 중수지절 관절 트랙션 + 배측 활주 (tech-A-013)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '중수지절 관절 트랙션 + 배측 활주',
  'MCP Joint Traction and Dorsal Glide',
  'MCP Tract+DG',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'wrist_hand'::body_region,
  '중수지절 관절(metacarpophalangeal joint)',
  false,
  '중수지절(MCP) 관절에 장축 견인(traction) 또는 배측 활주(dorsal glide)를 적용하여 손가락 굴곡 ROM을 회복하는 Kaltenborn 기법.',
  '[{"step":1,"instruction":"환자 앉아 팔꿈치 굴곡. 목표 손가락 MCP를 10–20° 굴곡(resting position)."},{"step":2,"instruction":"고정손 엄지·검지로 목표 중수골 원위부를 잡아 고정."},{"step":3,"instruction":"이동손 엄지·검지로 근위지골 근위부를 잡기."},{"step":4,"instruction":"트랙션(장축 견인): Kaltenborn Grade 2 — 30초 sustained hold. 통증 조절 또는 관절 이완 목적."},{"step":5,"instruction":"배측 활주(dorsal glide): 지골을 배측으로 글라이드 → 굴곡 ROM 개선. Grade에 따라 반복·진폭 조절."}]'::jsonb,
  '앉은 자세, 손바닥 치료대 위, 목표 MCP 10–20° 굴곡',
  '환자 측방',
  '고정손: 중수골 원위부. 이동손: 근위지골 근위부',
  '장축 견인(traction) 또는 배측(dorsal) 활주',
  '{"rom_improvement"}',
  '{"chronic","post_surgical","subacute"}',
  '{}',
  '{"fracture","instability","inflammation_acute"}',
  'level_2b'::evidence_level,
  '[{"pmid":"23347869","title":"Hand therapy joint mobilization for ROM","year":2013}]'::jsonb,
  '류마티스 관절염 환자는 Grade I 트랙션만 사용; Grade III 이상 금기. 소관절 가동술은 촉진 정확도가 매우 중요.',
  '급성 관절염, 인대 불안정',
  '류마티스 관절염 활동기',
  true,
  false
);

-- [14/42] 고관절 장축 견인 가동술 (tech-A-014)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '고관절 장축 견인 가동술',
  'Hip Long-Axis Distraction Mobilization',
  'Hip LADM',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'hip'::body_region,
  '고관절(hip joint) — 대퇴골두 + 비구',
  false,
  'Kaltenborn 기법으로 고관절을 장축 방향(ventral-lateral-caudal 벡터)으로 견인하여 관절 내 공간 증가, ROM 회복, 통증 감소를 목표로 하는 sustained traction 기법. 고관절 OA 1차 선택 기법.',
  '[{"step":1,"instruction":"환자 앙와위. 고관절 30° 굴곡 + 15° 외전 + 약간 외회전(MLPP, loose-packed position)."},{"step":2,"instruction":"골반 belt 또는 치료사 보조로 골반 ASIS 고정."},{"step":3,"instruction":"치료 belt를 대퇴 원위부(무릎 근위)에 걸거나 양손으로 원위 대퇴 감싸기."},{"step":4,"instruction":"Kaltenborn Grade 1: 슬랙만 제거 — 30초 sustained. 통증 조절 목적. Grade 2: 슬랙 완전 제거 + 조직 긴장 — 30–40초 × 3–5회."},{"step":5,"instruction":"Grade 3: 최대 신장(~200N 수준) — 30–40초 × 3–5회. 체중 후방 이동으로 힘 전달."},{"step":6,"instruction":"치료 후 고관절 굴곡·외전·내회전 ROM 비교 재평가."}]'::jsonb,
  '앙와위, MLPP(30° 굴곡, 15° 외전, 약간 외회전)',
  '환자 발쪽에 위치, 체중 후방 이동 준비. mobilization belt 사용 권장',
  'mobilization belt를 대퇴 원위부에 걸어 치료사 어깨·요추에 연결, 또는 양손 원위 대퇴 감싸기',
  '대퇴 장축(ventral-lateral-caudal) 방향 견인',
  '{"pain_relief","rom_improvement"}',
  '{"chronic","elderly","post_surgical","subacute"}',
  '{"knee_oa"}',
  '{"fracture","instability","inflammation_acute"}',
  'level_1b'::evidence_level,
  '[{"pmid":"17428705","title":"Hip mobilization for osteoarthritis: RCT","year":2007},{"pmid":"17483407","title":"Manual therapy for hip osteoarthritis: systematic review","year":2007}]'::jsonb,
  '고관절 OA에서 가장 근거가 강한 가동술 기법. Belt 사용 시 치료사 요추 부담 대폭 감소. 30–40초 sustained hold가 핵심 — 짧은 반복은 효과 감소. YouTube 보충: 변형 피크는 첫 15초 내에 발생하므로 30–40초 유지 프로토콜이 생물학적으로 정당화됨.',
  '대퇴골두 무혈성 괴사 진행성, 급성 고관절 골절',
  '급성 고관절 관절낭염, 고관절 불안정',
  true,
  false
);

-- [15/42] 고관절 후방 활주 가동술 (tech-A-015)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '고관절 후방 활주 가동술',
  'Hip Posterior Glide Mobilization',
  'Hip Post Glide',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'hip'::body_region,
  '고관절(hip joint) — 대퇴골두 후방 활주',
  false,
  '고관절 90° 굴곡 자세에서 대퇴골두를 후방으로 활주시켜 고관절 굴곡·내회전 ROM을 회복하는 Maitland 기법. OA 및 요추-골반-고관절 복합 기능장애에 적용.',
  '[{"step":1,"instruction":"환자 앙와위. 고관절 90° 굴곡 + 무릎 90° 굴곡."},{"step":2,"instruction":"치료사 어깨 또는 팔로 다리 지지. 골반 고정(치료대 또는 보조 치료사)."},{"step":3,"instruction":"양손으로 대퇴 근위 전면에 접촉하거나 mobilization belt 활용."},{"step":4,"instruction":"대퇴골두를 후방(posterior) 방향으로 활주. Grade II: 저항 이전. Grade III: 저항 속. Grade IV: 저항 끝."},{"step":5,"instruction":"치료 후 고관절 굴곡·내회전 ROM 재평가."}]'::jsonb,
  '앙와위, 고관절 90° 굴곡, 무릎 90° 굴곡',
  '환자 발쪽. 무릎을 치료사 어깨에 얹어 지지',
  '양손 대퇴 근위 전면 또는 mobilization belt',
  '후방(posterior) 활주',
  '{"rom_improvement","pain_relief"}',
  '{"chronic","elderly","subacute"}',
  '{"knee_oa"}',
  '{"instability","fracture","inflammation_acute"}',
  'level_2b'::evidence_level,
  '[{"pmid":"17428705","title":"Hip manual therapy: RCT","year":2007}]'::jsonb,
  '고관절 내회전 제한에서 후방 활주 우선 시도. LBP 환자에서 고관절 함께 치료 시 요통 예후 개선(PMC3172945). 서혜부 날카로운 통증 즉시 중단.',
  '고관절 전방 불안정, 급성 골절',
  '급성 관절낭염',
  true,
  false
);

-- [16/42] 경골 후방 활주 가동술 (굴곡 개선) (tech-A-016)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '경골 후방 활주 가동술 (굴곡 개선)',
  'Tibiofemoral Posterior Glide Mobilization',
  'TF Post Glide',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'knee'::body_region,
  '경골대퇴관절(tibiofemoral joint)',
  false,
  '경골(tibia)을 후방으로 활주시켜 무릎 굴곡 ROM을 회복하는 Maitland/Kaltenborn 기법. TKA 재활, ACL 재건 후 굴곡 제한에 가장 근거가 충분한 기법.',
  '[{"step":1,"instruction":"환자 앙와위. 무릎 약 25–30° 굴곡(resting position). 베개로 지지."},{"step":2,"instruction":"고정손으로 대퇴골 원위부를 치료대에 단단히 고정."},{"step":3,"instruction":"이동손 양 엄지 또는 thenar를 경골 근위 전면(tibial plateau 전방)에 접촉."},{"step":4,"instruction":"경골을 후방(posterior) 방향으로 활주. Grade II: 저항 이전 60초. Grade III: 저항 속 대진폭. Grade IV: R2 끝 소진폭."},{"step":5,"instruction":"Kaltenborn Grade 2·3: 30–40초 sustained hold. 치료 후 무릎 굴곡 ROM 측정."}]'::jsonb,
  '앙와위, 무릎 25–30° 굴곡, 베개 지지',
  '환자 발쪽 또는 무릎 측방',
  '이동손 양 엄지·thenar를 경골 근위 전면에 접촉',
  '후방(posterior) 활주',
  '{"rom_improvement"}',
  '{"post_surgical","chronic","subacute"}',
  '{"knee_oa","patellofemoral"}',
  '{"instability","fracture","inflammation_acute"}',
  'level_1b'::evidence_level,
  '[{"pmid":"20618697","title":"Tibiofemoral posterior glide for ACL rehabilitation: RCT","year":2010},{"pmid":"21087165","title":"Knee mobilization for flexion ROM after TKA","year":2011}]'::jsonb,
  'TKA 후 조기 재활에서 경골 후방 글라이드 + CPM 병행 시 굴곡 회복 빠름. 무릎 25° 굴곡이 최적 resting position(30°보다 정확). ACL 재건 후 전방 글라이드(신전 개선)와 후방 글라이드(굴곡 개선)를 목적에 따라 전환.',
  'ACL 불안정(전방 압력 금기), 급성 무릎 골절',
  '급성 무릎 관절염, 심한 관절 삼출',
  true,
  false
);

-- [17/42] 슬개골 상하 활주 가동술 (tech-A-017)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '슬개골 상하 활주 가동술',
  'Patellar Superior-Inferior Glide',
  'Patella Glide',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'knee'::body_region,
  '슬개대퇴관절(patellofemoral joint)',
  false,
  '슬개골을 상방(superior) 또는 하방(inferior)으로 활주시켜 무릎 신전·굴곡 ROM 및 슬개대퇴 통증을 개선하는 Maitland 기법.',
  '[{"step":1,"instruction":"환자 앙와위. 무릎 완전 신전 또는 약 10° 굴곡. 대퇴사두근 완전 이완 확인."},{"step":2,"instruction":"양손 엄지·검지로 슬개골 상극(superior pole) 또는 하극(inferior pole) 잡기."},{"step":3,"instruction":"하방 활주(inferior glide): 상극 접촉 → 미측 방향. 무릎 신전 ROM 및 슬개건 긴장 증가."},{"step":4,"instruction":"상방 활주(superior glide): 하극 접촉 → 두측 방향."},{"step":5,"instruction":"Grade I·II: 부드러운 진동, 60초. Grade III: 저항 속 대진폭."}]'::jsonb,
  '앙와위, 무릎 완전 신전 또는 10° 굴곡, 대퇴사두근 이완',
  '환자 측방',
  '양손 엄지·검지로 슬개골 상극 또는 하극 잡기',
  '슬개골 상방(superior) 또는 하방(inferior) 활주',
  '{"pain_relief","rom_improvement"}',
  '{"chronic","post_surgical","subacute"}',
  '{"patellofemoral","knee_oa"}',
  '{"instability","fracture"}',
  'level_2b'::evidence_level,
  '[{"pmid":"21087165","title":"Patellofemoral mobilization after TKA","year":2011}]'::jsonb,
  'TKA 후 슬개골 상하 가동성 감소 흔함 — 수술 후 2–3주부터 Grade I·II로 조기 시작 권장. 내외측 활주 병행 시 더 포괄적 슬개대퇴 관리 가능.',
  '슬개골 불안정, 급성 슬개건 파열',
  '급성 슬개골 골절, 슬개골 치환술 후',
  true,
  false
);

-- [18/42] 거퇴관절 후방 활주 가동술 (tech-A-018)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '거퇴관절 후방 활주 가동술',
  'Talocrural Posterior Talar Glide Mobilization',
  'TC Post Glide',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'ankle_foot'::body_region,
  '거퇴관절(talocrural joint, ankle mortise)',
  false,
  '거골(talus)을 후방으로 활주시켜 발목 배측굴곡 ROM을 회복하는 Maitland 기법. 발목 염좌 후 강직, 만성 발목 불안정, 아킬레스건 수술 후에 적용.',
  '[{"step":1,"instruction":"환자 앙와위. 발목을 치료대 끝 밖으로 내놓거나 치료사가 지지. 발목 중립 또는 약 10° 배측굴곡. 슬관절 약간 굴곡."},{"step":2,"instruction":"고정손으로 하퇴 원위부(경골·비골 원위)를 단단히 고정."},{"step":3,"instruction":"이동손으로 거골 상면(dome) 또는 목 부위를 손바닥 전면으로 접촉."},{"step":4,"instruction":"거골을 후방(posterior) 방향으로 활주. Grade II: 저항 이전 60초. Grade III: 저항 속 대진폭. Grade IV: R2 끝 소진폭."},{"step":5,"instruction":"치료 후 배측굴곡 ROM 측정(weight-bearing lunge test 권장)."}]'::jsonb,
  '앙와위, 발목 치료대 끝 밖으로, 중립 또는 10° 배측굴곡, 슬관절 약간 굴곡',
  '환자 발 측방 또는 하방',
  '고정손: 하퇴 원위부. 이동손: 거골 상면(외측 발등 위)',
  '후방(posterior) 활주',
  '{"rom_improvement","pain_relief"}',
  '{"subacute","chronic","athlete","post_surgical"}',
  '{"ankle_sprain"}',
  '{"fracture","instability"}',
  'level_1b'::evidence_level,
  '[{"pmid":"16717267","title":"Talocrural posterior glide for dorsiflexion ROM: RCT","year":2006}]'::jsonb,
  '발목 염좌 후 배측굴곡 제한은 재부상 위험 인자 — 조기 가동술로 ROM 회복 필수. Mulligan WB MWM과 병행 시 더 즉각적이고 지속적 효과. Weight-bearing lunge test로 치료 전·후 각도 측정 권장.',
  '급성 발목 골절, 거골 무혈성 괴사',
  '완전 인대 파열(Grade III) 불안정',
  true,
  false
);

-- [19/42] 거골하 관절 내외측 활주 가동술 (tech-A-019)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '거골하 관절 내외측 활주 가동술',
  'Subtalar Mediolateral Glide Mobilization',
  'STJ ML Glide',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'ankle_foot'::body_region,
  '거골하 관절(subtalar joint)',
  false,
  '종골(calcaneus)을 내측(medial) 또는 외측(lateral)으로 활주시켜 거골하 관절의 내·외번 ROM을 회복하는 Maitland 기법. 만성 발목 불안정(CAI), 편평족 관련 기능 제한에 적용.',
  '[{"step":1,"instruction":"환자 측와위(목표 발이 위로) 또는 앙와위. 발목 중립, 슬관절 약간 굴곡."},{"step":2,"instruction":"고정손으로 거골 내측 또는 외측 고정."},{"step":3,"instruction":"이동손으로 종골 내측 또는 외측을 손바닥으로 감싸 접촉."},{"step":4,"instruction":"외번 개선: 내측 글라이드(종골 → 내측), Grade II·III, 60초 × 3세트. 내번 개선: 외측 글라이드(종골 → 외측)."},{"step":5,"instruction":"치료 후 거골하 내·외번 ROM 및 보행 안정성 비교 재평가."}]'::jsonb,
  '측와위(목표 발 위) 또는 앙와위, 발목 중립',
  '환자 발 측방',
  '고정손: 거골 내·외측. 이동손: 종골을 손바닥으로 감싸 파지',
  '내측(medial) 또는 외측(lateral) 활주',
  '{"rom_improvement","stabilization"}',
  '{"chronic","athlete","subacute"}',
  '{"ankle_sprain"}',
  '{"fracture"}',
  'level_2b'::evidence_level,
  '[{"pmid":"26462506","title":"Subtalar mobilization for chronic ankle instability","year":2015}]'::jsonb,
  '만성 발목 불안정 환자에서 외번 약화와 거골하 내측 글라이드 제한이 동반되는 경우 많음. 근력 강화와 병행 필수 — 가동술만으로는 안정성 회복 불충분.',
  '거골하 골절, 관절 융합술 후',
  '급성 발목 염좌(Grade III)',
  true,
  false
);

-- [20/42] 고관절 견인 + 내회전 가동술 (추가) (tech-A-020)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '고관절 견인 + 내회전 가동술 (추가)',
  'Hip Traction with Internal Rotation',
  'Hip Tract+IR',
  'category_a_joint_mobilization'::technique_category,
  'Maitland',
  'hip'::body_region,
  '고관절(hip joint) — 내회전 ROM 특화',
  false,
  '고관절 장축 견인을 유지하면서 내회전 방향의 가동술을 병행하여 고관절 내회전 ROM을 특화적으로 회복하는 복합 기법. 고관절 OA, FAI 관련 내회전 제한에 적용.',
  '[{"step":1,"instruction":"환자 앙와위. 고관절 MLPP(30° 굴곡, 15° 외전, 약간 외회전)."},{"step":2,"instruction":"골반 고정(belt 또는 보조 치료사). mobilization belt로 장축 견인 준비."},{"step":3,"instruction":"장축 견인(Kaltenborn Grade 2) 유지 상태에서 내회전 방향으로 조심스러운 가동술 추가."},{"step":4,"instruction":"Grade II·III 수준 내회전 가동술: 저항 느껴지는 범위까지 반복. 30–40초 × 3세트."},{"step":5,"instruction":"치료 후 내회전 ROM 및 서혜부 통증 변화 재평가."}]'::jsonb,
  '앙와위, MLPP(30° 굴곡, 15° 외전, 약간 외회전)',
  '환자 발쪽, mobilization belt 착용',
  'mobilization belt: 대퇴 원위부. 추가 내회전 가동 시 손으로 원위 대퇴 파지',
  '장축 견인(distraction) + 내회전(internal rotation) 복합',
  '{"rom_improvement","pain_relief"}',
  '{"chronic","elderly","subacute","athlete"}',
  '{"knee_oa"}',
  '{"fracture","instability","inflammation_acute"}',
  'level_2b'::evidence_level,
  '[{"pmid":"17428705","title":"Hip manual therapy OA: RCT","year":2007}]'::jsonb,
  '고관절 OA에서 내회전 제한이 주증상일 때 LADM 단독보다 내회전 복합 기법이 더 특화된 ROM 개선. 급성기에는 LADM만 먼저 적용 후 안정화된 후 복합 적용.',
  '대퇴골두 무혈성 괴사 진행성, 급성 골절',
  '급성 관절낭염, 고관절 불안정',
  true,
  false
);

-- [21/42] 경추 SNAG (tech-B-001)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '경추 SNAG',
  'Cervical Sustained Natural Apophyseal Glide',
  'Cx SNAG',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'cervical'::body_region,
  '경추 분절 C2–C7 추간관절(facet joint)',
  false,
  '치료사가 경추 관절돌기에 치료면(facet plane) 방향으로 활주를 유지하면서 환자가 제한된 방향으로 능동 운동을 수행하는 Mulligan SNAG 기법. No Pain Rule 적용. 경추 ROM 제한, 경추성 두통, WAD에 적용.',
  '[{"step":1,"instruction":"사전 기준 동작 확인: 통증 유발 운동 방향과 ROM 기록."},{"step":2,"instruction":"환자 앉은 자세. 치료사 후방 또는 측방 위치. 목표 분절 위 척추체 관절돌기에 두상골 또는 엄지 척측면 접촉."},{"step":3,"instruction":"활주 방향 탐색: 치료면(수평면에서 약 45° 상방) 방향 활주 → 무통 여부 확인 → 안 되면 내측/외측 방향 ±10° 조정."},{"step":4,"instruction":"No Pain Rule 확인: 활주 유지 상태에서 환자 능동 운동 시 즉각 VAS 0 확인. 통증 있으면 방향 재탐색."},{"step":5,"instruction":"환자에게 제한 방향 능동 운동 지시 (굴곡/신전/회전/측굴). 활주 유지하며 끝 범위 3–6초 유지."},{"step":6,"instruction":"10회 × 3세트(표준). 급성기 5회 × 3세트. 세션 후 ROM 재측정."}]'::jsonb,
  '앉은 자세, 발바닥 바닥 닿음, 척추 중립',
  '환자 측방 또는 후방, 한 발 앞에 두어 중심 안정',
  '두상골(pisiform) 또는 엄지 척측면을 위 척추체 관절돌기에 접촉. 5번째 손가락 중간 마디를 극돌기 아래에 걸기도 함',
  '치료면 방향(수평면에서 약 45° 상방) 두측(cephalad) 활주',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic","athlete"}',
  '{"cervicogenic_ha","radiculopathy"}',
  '{"instability","malignancy","fracture","vbi_risk"}',
  'level_1b'::evidence_level,
  '[{"pmid":"28110866","title":"Cervical SNAG for neck pain and ROM: RCT (Hidalgo 2017)","year":2017}]'::jsonb,
  '방향 탐색 실패 시 치료면 각도 ±10° 조정 또는 외측 방향 추가. Self-SNAG: 타월 또는 Mulligan Strap으로 가정 교육. 경추 회전 제한 + 경추성 두통 조합에서 Self-SNAG 순응도 높음. 처음 1–3회 반복에서 즉각 효과 없으면 기법 재평가.',
  '경추 불안정(RA, 외상), 골절, 종양, VBI 불충분',
  '심한 골다공증, 급성 추간판 탈출 신경 증상 심한 경우',
  true,
  false
);

-- [22/42] 경추 NAG (tech-B-002)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '경추 NAG',
  'Cervical Natural Apophyseal Glide',
  'Cx NAG',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'cervical'::body_region,
  '경추 중위부 C3–C7 및 경흉 이행부',
  false,
  '치료사가 경추 분절에 치료면 방향으로 리드미컬한 수동 활주를 제공하는 Mulligan NAG 기법. 환자는 능동 운동 없이 이완 자세 유지. SNAG 전 준비 기법 또는 고령 환자 첫 세션에 활용.',
  '[{"step":1,"instruction":"사전 기준 동작 확인: 굴곡·신전 ROM 및 통증 파악."},{"step":2,"instruction":"환자 앉은 자세, 척추 중립. 치료사 측방 또는 후방."},{"step":3,"instruction":"팔파로 hypomobile 분절 확인. 엄지로 상위 척추체 횡돌기 접촉."},{"step":4,"instruction":"치료면 방향으로 초당 1–2회 리듬적 활주 적용(Grade II–III 수준). 환자는 이완 자세 유지."},{"step":5,"instruction":"활주 중 통증 없어야 함(No Pain Rule). 6–10회 × 3세트. ROM 재측정."}]'::jsonb,
  '앉은 자세, 척추 중립, 이완 자세',
  '환자 측방 또는 후방',
  '엄지 또는 두상골을 상위 척추체 횡돌기에 접촉',
  '치료면 방향(약 45° 상방) 리드미컬 활주',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic","elderly"}',
  '{"cervicogenic_ha"}',
  '{"instability","malignancy","fracture","vbi_risk"}',
  'level_2b'::evidence_level,
  '[{"pmid":"28110866","title":"Mulligan concept cervical techniques: review","year":2017}]'::jsonb,
  'NAG는 주로 SNAG 전 준비 기법. Self-NAG 없음. 고령 경추 강직 환자에서 SNAG 전 NAG로 조직 준비 후 적용 시 순응도 개선.',
  '경추 불안정, 골절, 종양, VBI 불충분',
  '심한 골다공증',
  true,
  false
);

-- [23/42] 경추 Reverse NAG (tech-B-003)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '경추 Reverse NAG',
  'Cervical Reverse Natural Apophyseal Glide',
  'Cx Rev NAG',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'cervical'::body_region,
  '상위 경추 C0–C3 전방 구조',
  false,
  '상위 경추 전방 구조를 후방-상방으로 리드미컬하게 활주하여 경추 굴곡 ROM을 개선하는 Mulligan Reverse NAG 기법. SNAG 효과 부족한 굴곡 제한에 추가 적용.',
  '[{"step":1,"instruction":"사전 기준 동작: 경추 굴곡 제한 확인."},{"step":2,"instruction":"환자 앉은 자세. 치료사 측방. 두 번째 손가락 중간 마디(middle phalanx)를 C1–C3 전방(턱 아래 연조직)에 접촉. 고정손으로 후두골 지지."},{"step":3,"instruction":"전방 구조를 후방-상방으로 1–2Hz 리듬적 활주. 매우 부드럽게 — 연조직 압박 최소화."},{"step":4,"instruction":"통증 없어야 함. 6–10회 × 3세트."},{"step":5,"instruction":"굴곡 ROM 재측정."}]'::jsonb,
  '앉은 자세, 머리 중립',
  '환자 측방',
  '2번째 손가락 중간 마디를 C1–C3 전방 연조직에 접촉',
  '후방-상방(posterior-cranial) 리드미컬 활주',
  '{"rom_improvement"}',
  '{"subacute","chronic"}',
  '{"cervicogenic_ha"}',
  '{"instability","vbi_risk"}',
  'level_3'::evidence_level,
  '[{"pmid":"28110866","title":"Mulligan concept: clinical evidence review","year":2017}]'::jsonb,
  '적용 전 전방 경부 조직 민감도 확인 필수. 연하곤란·호흡 불편감 유발 시 즉시 중단(전방 구조 압박 과다). 한국 임상 적용 빈도 낮음 — SNAG 효과 부족한 굴곡 제한에 한해 시도.',
  '전방 경부 수술력, 경동맥 질환, 경추 불안정',
  '연하장애 기왕력',
  true,
  false
);

-- [24/42] C1–C2 SNAG (환추축추 SNAG) (tech-B-004)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  'C1–C2 SNAG (환추축추 SNAG)',
  'C1-C2 Atlanto-Axial SNAG',
  'C1C2 SNAG',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'cervical'::body_region,
  '환추축추 관절(C1–C2, atlanto-axial joint)',
  false,
  'C1 횡돌기를 측방(회전 방향)으로 활주하면서 환자가 능동 회전하는 Mulligan SNAG 기법. 상위 경추 회전 제한, 경추성 두통에 적용. 반드시 불안정성 스크리닝 선행 필수.',
  '[{"step":1,"instruction":"불안정성 스크리닝 선행: Sharp-Purser test, Alar ligament test 등으로 C1–C2 불안정성 배제 필수."},{"step":2,"instruction":"회전 ROM 기록 및 통증 방향 확인."},{"step":3,"instruction":"환자 앉은 자세. 치료사 후방 또는 측방. C1 횡돌기(후방)에 엄지 또는 두상골 접촉. 고정손으로 반대편 두개골 지지."},{"step":4,"instruction":"활주 방향 탐색: C1 횡돌기를 회전 방향으로 측방 활주 → 무통 회전 ROM 개선 확인."},{"step":5,"instruction":"활주 유지하며 환자 능동 회전. 10회 × 3세트. 재평가."}]'::jsonb,
  '앉은 자세, 척추 중립',
  '환자 후방 또는 측방',
  '엄지 또는 두상골을 C1 횡돌기(후방)에 접촉',
  '측방(회전 방향) 활주',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic"}',
  '{"cervicogenic_ha"}',
  '{"instability","malignancy","fracture","vbi_risk"}',
  'level_1b'::evidence_level,
  '[{"pmid":"17327196","title":"C1-C2 SNAG for cervicogenic headache: RCT (Hall 2007)","year":2007}]'::jsonb,
  '반드시 불안정성 스크리닝 선행. Self-SNAG: 타월을 C1 횡돌기에 걸고 스스로 측방 활주 + 회전. YouTube 보충: Self-SNAG 3×10회 × 10초 유지, 하루 2회, 12개월 시 두통 54% 감소.',
  'C1–C2 불안정(RA, 다운증후군, 외상), 골절, 종양',
  '불안정성 스크리닝 미완료 시',
  true,
  false
);

-- [25/42] 흉추 SNAG (tech-B-005)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '흉추 SNAG',
  'Thoracic Sustained Natural Apophyseal Glide',
  'Tx SNAG',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'thoracic'::body_region,
  '흉추 분절 T1–T12',
  false,
  '치료사가 흉추 극돌기 또는 횡돌기에 두상골로 치료면 방향 활주를 유지하면서 환자가 제한된 흉추 운동을 수행하는 Mulligan SNAG 기법. 흉추 강직, 어깨 ROM 제한과 연관된 흉추 기능장애에 적용.',
  '[{"step":1,"instruction":"사전 기준 동작 확인: 흉추 ROM 및 통증 분절 확인. 팔파로 hypomobility 분절 확인."},{"step":2,"instruction":"환자 앉은 자세(회전·측굴용) 또는 엎드린 자세(신전용). 팔을 가슴 앞 교차 또는 머리 뒤 깍지."},{"step":3,"instruction":"치료사 측방 또는 후방. 두상골로 극돌기 측방 접촉. 활주 방향: 흉추 치료면(수평면에서 약 60° 상방) 방향."},{"step":4,"instruction":"활주 방향 탐색 → 무통 여부 확인. 환자 제한 방향 능동 운동 지시."},{"step":5,"instruction":"10회 × 3세트. 흉추 신전 제한에 Mulligan tape 연계 가능."}]'::jsonb,
  '앉은 자세(회전·측굴) 또는 엎드린 자세(신전). 팔 가슴 교차',
  '환자 측방 또는 후방',
  '두상골을 목표 흉추 극돌기 측방 또는 횡돌기에 접촉',
  '치료면 방향(수평면에서 약 60° 상방) 활주',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic","athlete"}',
  '{"lbp_nonspecific"}',
  '{"osteoporosis","malignancy","fracture"}',
  'level_2b'::evidence_level,
  '[{"pmid":"18337090","title":"Thoracic SNAG for thoracic mobility: clinical study (Moutzouri 2008)","year":2008}]'::jsonb,
  '어깨 문제 동반 시 흉추 SNAG 먼저 적용 → 어깨 ROM 간접 개선 효과. Self-SNAG: foam roller로 자가 흉추 신전 SNAG 교육. 사무직 흉추 강직에 흉추 SNAG + 자가 신전 운동 병행 효과적.',
  '골다공증성 골절, 종양, 불안정성',
  '골다공증, 늑골 이상',
  true,
  false
);

-- [26/42] 늑골 SNAG (tech-B-006)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '늑골 SNAG',
  'Rib SNAG',
  'Rib SNAG',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'rib'::body_region,
  '늑척추 관절(costovertebral joint), 늑횡돌기 관절(costotransverse joint)',
  false,
  '늑골 각도(posterior rib angle)에 활주를 유지하면서 환자가 심호흡 또는 흉추 회전을 수행하는 Mulligan SNAG 기법. 흡기 통증, 늑척추 관절 기능부전에 적용.',
  '[{"step":1,"instruction":"사전 기준 동작: 흡기 시 통증 방향 및 ROM 확인. 팔파로 압통 늑골 각도 확인."},{"step":2,"instruction":"환자 앉거나 엎드린 자세. 치료사 후방 측방."},{"step":3,"instruction":"두상골 또는 엄지를 늑골 후방 각도(posterior angle)에 접촉. 활주 방향 탐색: 전방·하방·측방 순 시도."},{"step":4,"instruction":"활주 유지하며 환자 천천히 심호흡 또는 흉추 회전. 통증 소실 확인."},{"step":5,"instruction":"6–10회 × 3세트."}]'::jsonb,
  '앉거나 엎드린 자세',
  '환자 후방 측방',
  '두상골 또는 엄지를 늑골 후방 각도에 접촉',
  '전방(anterior), 하방(caudal), 또는 측방(lateral) 활주 — 방향 탐색',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic"}',
  '{}',
  '{"fracture","osteoporosis"}',
  'level_3'::evidence_level,
  '[{"pmid":"28110866","title":"Mulligan concept clinical applications: review","year":2017}]'::jsonb,
  '흉추 SNAG와 병행하면 흉부 ROM 극대화. 심한 늑골 통증 시 골절 배제 필수. 흉부 압박감 악화 즉시 중단.',
  '늑골 골절, 늑막염, 기흉 의심',
  '골다공증, 늑골 이상',
  true,
  false
);

-- [27/42] 요추 SNAG (tech-B-007)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '요추 SNAG',
  'Lumbar Sustained Natural Apophyseal Glide',
  'L SNAG',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'lumbar'::body_region,
  '요추 분절 L1–L5',
  false,
  '서기 자세에서 치료사가 요추 극돌기에 두상골로 상방 활주를 유지하면서 환자가 제한된 요추 운동을 수행하는 Mulligan SNAG 기법. 요통, 요추 ROM 제한, 초기 신경근병증에 적용.',
  '[{"step":1,"instruction":"사전 기준 동작 확인: 요추 굴곡/신전 ROM 및 통증 각도 기록."},{"step":2,"instruction":"환자 서기 자세(기능적 — Belt SNAG과 달리 손만 사용). 양발 어깨 넓이."},{"step":3,"instruction":"치료사 후방. 두상골로 목표 분절 극돌기 측방 접촉. 활주 방향: 요추 치료면(거의 수직 상방) 방향."},{"step":4,"instruction":"활주 방향 탐색 → 무통 확인. 환자 굴곡·신전 지시. 통증 소실 확인(VAS 0)."},{"step":5,"instruction":"10회 × 3세트. Self-SNAG 교육: 벨트·타월로 자가 적용."}]'::jsonb,
  '서기 자세(standing), 양발 어깨 너비',
  '환자 후방, 한 발 앞에 두어 체중 이동',
  '두상골(pisiform)을 목표 요추 극돌기 직외측에 접촉',
  '상방(수직에 가까운) 활주 — 요추 치료면 방향',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic","athlete"}',
  '{"lbp_nonspecific","radiculopathy"}',
  '{"instability","malignancy","fracture"}',
  'level_1b'::evidence_level,
  '[{"pmid":"17483407","title":"Lumbar SNAG for low back pain: RCT (Konstantinou 2007)","year":2007}]'::jsonb,
  '하지 방사통 악화 즉시 중단. Self-SNAG HEP: 침대 옆에서 타월 기법으로 순응도 높음. 손 활주 힘 부족 시 Belt SNAG으로 업그레이드.',
  '마미증후군, 척추 종양, 급성 골절, 복부 대동맥류 의심',
  '심한 급성 추간판 탈출 신경 증상',
  true,
  false
);

-- [28/42] 요추 Belt SNAG (tech-B-008)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '요추 Belt SNAG',
  'Lumbar Belt SNAG',
  'L Belt SNAG',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'lumbar'::body_region,
  '요추 분절 L3–L5 / 요천 이행부',
  false,
  '치료 벨트를 이용하여 손 접촉보다 더 강하고 일정한 활주를 제공하는 Mulligan SNAG 업그레이드 기법. 서기 자세 유지 + 벨트로 상방 활주. 체격이 크거나 심한 강직 환자에 우선 적용.',
  '[{"step":1,"instruction":"사전 기준 동작: 굴곡 ROM 및 통증 각도 기록."},{"step":2,"instruction":"환자 서기 자세. 치료 벨트를 목표 분절 극돌기 직하방에 위치."},{"step":3,"instruction":"치료사 허리에 벨트 걸어 체중으로 힘 제공. 무릎 굴곡으로 중심 낮춤."},{"step":4,"instruction":"벨트를 상방으로 당겨 일정한 활주 유지. 환자 굴곡 지시: ''허리를 앞으로 최대한 굽혀보세요''."},{"step":5,"instruction":"통증 소실 확인. 10회 × 3세트. Self-Belt SNAG 가정 교육."}]'::jsonb,
  '서기 자세(weight-bearing), 양발 어깨 너비',
  '환자 후방, 무릎 굴곡, 벨트 치료사 허리에 고정',
  '치료 벨트를 목표 분절 극돌기 직하방에 위치',
  '벨트를 통한 상방(cephalad) 활주',
  '{"pain_relief","rom_improvement"}',
  '{"chronic","athlete","subacute"}',
  '{"lbp_nonspecific"}',
  '{"instability","malignancy","fracture"}',
  'level_2b'::evidence_level,
  '[{"pmid":"17483407","title":"Lumbar SNAG techniques: clinical evidence","year":2007}]'::jsonb,
  '손 SNAG 힘 부족 시 Belt SNAG 전환. 체격 큰 남성 요통에서 Belt SNAG이 손 SNAG보다 즉각 효과 우수. Self-Belt SNAG: 가정에서 침대 헤드보드나 문 손잡이에 타월 걸어 자가 적용 교육.',
  '마미증후군, 척추 종양, 급성 골절',
  '심한 급성 추간판 탈출',
  true,
  false
);

-- [29/42] 견관절 MWM — 외전 (tech-B-009)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '견관절 MWM — 외전',
  'Glenohumeral MWM Abduction',
  'GH MWM Abd',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'shoulder'::body_region,
  '견관절(glenohumeral joint)',
  false,
  '상완골두 전방에 후방 활주를 유지하면서 환자가 어깨 외전을 수행하는 Mulligan MWM 기법. 외전 제한, painful arc, 충돌 증후군에 적용. 치료 벨트 사용 시 self-MWM 교육 연계.',
  '[{"step":1,"instruction":"사전 기준 동작: 외전 ROM 및 통증 각도(painful arc) 기록."},{"step":2,"instruction":"환자 앉거나 서기. 치료사 측방. 상완골두 전방에 두상골 접촉."},{"step":3,"instruction":"활주 방향 탐색: 후방 → 하방 → 후하방 순으로 무통 방향 탐색."},{"step":4,"instruction":"활주 유지하며 환자 외전 지시. 팔이 올라가는 동안 활주 일정 유지."},{"step":5,"instruction":"통증 소실 확인(VAS 0, painful arc 소실). 10회 × 3세트."}]'::jsonb,
  '앉거나 서기, 시술 측 팔 이완',
  '환자 측방',
  '활주손: 상완골두 전방에 두상골. 고정손: 견봉 또는 scapula 안정화',
  '후방(posterior) 또는 후하방(posteroinferior) 활주',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic","athlete"}',
  '{"rotator_cuff","frozen_shoulder"}',
  '{"instability","fracture","inflammation_acute"}',
  'level_1b'::evidence_level,
  '[{"pmid":"18164458","title":"GH MWM for abduction ROM: RCT (Teys 2008)","year":2008}]'::jsonb,
  '충돌 증후군에서 후방 활주 방향이 가장 효과적; arc of pain 사라지면 즉각 Self-MWM 교육. belt anchor: 상완골두 전방에서 치료사 고관절까지 연결. 후외측-하방 벡터. YouTube 보충: 벨트 고정 위치 = 상완골두 바로 원위.',
  '완전 회전근개 파열, 견관절 불안정',
  '급성 고자극성 염증, 최근 어깨 수술',
  true,
  false
);

-- [30/42] 견관절 MWM — 내회전 (tech-B-010)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '견관절 MWM — 내회전',
  'Glenohumeral MWM Internal Rotation',
  'GH MWM IR',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'shoulder'::body_region,
  '견관절(glenohumeral joint)',
  false,
  '상완골두 전방에 후방 활주를 유지하면서 환자가 어깨 내회전(등 뒤로 손 올리기)을 수행하는 Mulligan MWM 기법. GIRD(내회전 결손), 동결견에 적용.',
  '[{"step":1,"instruction":"사전 확인: 내회전 ROM(등 뒤로 손 위치) 기록."},{"step":2,"instruction":"환자 앉은 자세. 상완골두 전방에 두상골 접촉."},{"step":3,"instruction":"후방 활주 유지 + 환자 내회전(등 뒤로 손 올리기) 동시 수행."},{"step":4,"instruction":"통증 소실 확인. 10회 × 3세트."},{"step":5,"instruction":"Self-MWM: 치료 벨트 이용 후방 활주 자가 적용 후 내회전 스트레칭 교육."}]'::jsonb,
  '앉은 자세, 시술 측 팔 90° 외전 또는 신체 옆 내회전 자세',
  '환자 측방 또는 후방',
  '활주손: 상완골두 전방에 두상골. 고정손: 견봉/upper trapezius 지지',
  '후방(posterior) 활주',
  '{"rom_improvement"}',
  '{"subacute","chronic","athlete"}',
  '{"frozen_shoulder","rotator_cuff"}',
  '{"instability","inflammation_acute"}',
  'level_2b'::evidence_level,
  '[{"pmid":"18164458","title":"GH MWM techniques: clinical evidence","year":2008}]'::jsonb,
  '투구 선수 GIRD에서 탁월한 초기 치료 도구. Self-MWM 치료 벨트 이용 후방 활주 자가 적용 후 내회전 스트레칭.',
  '전방 불안정성, 심한 급성 염증',
  '회전근개 전층 파열',
  true,
  false
);

-- [31/42] 견관절 MWM — 외회전 (tech-B-011)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '견관절 MWM — 외회전',
  'Glenohumeral MWM External Rotation',
  'GH MWM ER',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'shoulder'::body_region,
  '견관절(glenohumeral joint)',
  false,
  '상완골두 후방에 전방 활주를 유지하면서 환자가 어깨 외회전을 수행하는 Mulligan MWM 기법. 외회전 제한, 동결견에 적용.',
  '[{"step":1,"instruction":"사전 확인: 외회전 ROM 기록."},{"step":2,"instruction":"환자 앉은 자세. 팔꿈치 90° 굴곡, 어깨 중립."},{"step":3,"instruction":"활주손: 상완골두 후방에 두상골 접촉. 전방 활주 유지."},{"step":4,"instruction":"전방 활주 유지 + 환자 외회전 동시 수행. 통증 소실 확인."},{"step":5,"instruction":"10회 × 3세트."}]'::jsonb,
  '앉은 자세, 팔꿈치 90° 굴곡, 전완 수평',
  '환자 측방',
  '활주손: 상완골두 후방에 두상골. 고정손: 팔꿈치 지지',
  '전방(anterior) 또는 하방(inferior) 활주',
  '{"rom_improvement"}',
  '{"subacute","chronic"}',
  '{"frozen_shoulder"}',
  '{"instability","inflammation_acute"}',
  'level_2b'::evidence_level,
  '[{"pmid":"18164458","title":"GH MWM techniques","year":2008}]'::jsonb,
  '동결견에서 외회전 MWM + 내회전 MWM 병행 시너지 효과. 전방 불안정성 환자에서 전방 활주 금기.',
  '전방 불안정성(anterior instability)',
  '급성 고자극성 염증',
  true,
  false
);

-- [32/42] 견관절 MWM — 굴곡 (tech-B-012)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '견관절 MWM — 굴곡',
  'Glenohumeral MWM Flexion',
  'GH MWM Flex',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'shoulder'::body_region,
  '견관절(glenohumeral joint)',
  false,
  '상완골두 전방에 후방-하방 활주를 유지하면서 환자가 어깨 굴곡을 수행하는 Mulligan MWM 기법. 굴곡 제한, 충돌 증후군에 적용.',
  '[{"step":1,"instruction":"사전 확인: 굴곡 ROM 기록."},{"step":2,"instruction":"환자 앉거나 서기. 활주손: 상완골두 전방에 두상골. 후방 활주 적용."},{"step":3,"instruction":"후방 활주 유지 + 환자 굴곡 동시 수행. 통증 소실 확인."},{"step":4,"instruction":"10회 × 3세트."}]'::jsonb,
  '앉거나 서기',
  '환자 측방',
  '활주손: 상완골두 전방에 두상골. 고정손: 견봉 또는 쇄골 지지',
  '후방(posterior) 또는 후하방 활주',
  '{"rom_improvement","pain_relief"}',
  '{"subacute","chronic","athlete"}',
  '{"frozen_shoulder","rotator_cuff"}',
  '{"instability","fracture"}',
  'level_2b'::evidence_level,
  '[{"pmid":"18164458","title":"GH MWM for shoulder ROM","year":2008}]'::jsonb,
  '굴곡 MWM과 외전 MWM을 순차 적용 시 전반적 어깨 ROM 회복 효율 높음.',
  '완전 회전근개 파열, 견관절 불안정',
  '급성 고자극성 염증',
  true,
  false
);

-- [33/42] 테니스 엘보 MWM (외측상과통 MWM) (tech-B-013)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '테니스 엘보 MWM (외측상과통 MWM)',
  'Tennis Elbow MWM (Lateral Epicondylalgia MWM)',
  'TE MWM',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'elbow'::body_region,
  '상완요골관절(radiohumeral joint) + 근위 요척관절',
  false,
  '전완에 외측 활주를 유지하면서 환자가 손목 신전 또는 악력을 수행하는 Mulligan MWM 기법. 외측상과통(테니스 엘보)에 가장 근거 수준이 높은 기법. 초진 즉각 통증 소실 효과.',
  '[{"step":1,"instruction":"사전 기준 동작: 그립 강도(dynamometer) 및 통증 VAS 기록. Cozen''s test 양성 확인."},{"step":2,"instruction":"환자 앉은 자세. 팔꿈치 신전 또는 약 30° 굴곡. 전완 회내 + 손목 약간 굴곡에서 시작."},{"step":3,"instruction":"고정손: 상완골 원위부 내측 고정. 활주손: 근위 요골 또는 요골두에서 외측 활주 적용."},{"step":4,"instruction":"외측 활주 방향 탐색 → 내측 회전 조합 시도. 그립 시 VAS 0 확인."},{"step":5,"instruction":"환자 손목 신전 또는 주먹 쥐기(grip). 10회 × 3세트."},{"step":6,"instruction":"치료 테이프 또는 팔꿈치 스트랩으로 self-MWM 교육."}]'::jsonb,
  '앉은 자세, 팔꿈치 신전~30° 굴곡, 전완 회내',
  '환자 측방',
  '고정손: 상완골 원위부 내측. 활주손: 근위 요골 외측 활주(압박 아닌 측방 활주)',
  '외측(lateral) 활주 — 약 5–10° 굴곡 방향 요소 추가 가능',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic","athlete"}',
  '{"lateral_epicondylalgia"}',
  '{"fracture","instability","inflammation_acute"}',
  'level_1b'::evidence_level,
  '[{"pmid":"11669625","title":"Tennis elbow MWM immediate effects: RCT (Vicenzino 2001)","year":2001},{"pmid":"17512783","title":"Mulligan MWM for lateral epicondylalgia: RCT (Vicenzino 2007)","year":2007}]'::jsonb,
  '가장 근거 수준이 높은 Mulligan 기법 중 하나. YouTube 보충: 그립 당 6초 유지, 즉각 58% 무통 그립 증가(Vicenzino). 한국 임상: 주부·사무직 외측상과통에서 초진에서 즉각 통증 소실로 신뢰 형성 효과 탁월.',
  '팔꿈치 골절, 심한 불안정성',
  '급성 염증기',
  true,
  false
);

-- [34/42] 팔꿈치 굴곡 MWM (tech-B-014)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '팔꿈치 굴곡 MWM',
  'Elbow Flexion MWM',
  'Elbow Flex MWM',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'elbow'::body_region,
  '상완요골·상완척골 관절',
  false,
  '전완에 내측 또는 외측 활주를 유지하면서 환자가 팔꿈치 굴곡을 수행하는 Mulligan MWM 기법. 팔꿈치 굴곡 제한, 수술 후 재활에 적용.',
  '[{"step":1,"instruction":"사전 기준 동작: 굴곡 ROM 기록."},{"step":2,"instruction":"환자 앉은 자세, 팔꿈치 신전에서 시작."},{"step":3,"instruction":"고정손: 상완골 원위부 고정. 활주손: 전완 근위부에서 내측 또는 외측 활주 탐색."},{"step":4,"instruction":"무통 방향 확인 후 활주 유지 + 환자 굴곡 동시 수행."},{"step":5,"instruction":"10회 × 3세트. 굴곡 ROM 재평가."}]'::jsonb,
  '앉은 자세, 팔꿈치 신전에서 시작',
  '환자 측방',
  '고정손: 상완골 원위부. 활주손: 전완 근위부 내측 또는 외측',
  '내측(medial) 또는 외측(lateral) 활주 — 방향 탐색',
  '{"rom_improvement"}',
  '{"post_surgical","subacute"}',
  '{}',
  '{"fracture","instability"}',
  'level_3'::evidence_level,
  '[{"pmid":"25269557","title":"Elbow MWM for flexion restriction","year":2014}]'::jsonb,
  '골절 후 팔꿈치 ROM 회복 재활에서 통증 없이 ROM 증가 가능. 굴곡 제한에서 내측 활주 방향이 더 효과적인 경우 많음.',
  '급성 골절, 내측 측부인대 불안정',
  '팔꿈치 수술 후 초기',
  true,
  false
);

-- [35/42] 손목 MWM (tech-B-015)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '손목 MWM',
  'Wrist MWM',
  'Wrist MWM',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'wrist_hand'::body_region,
  '요수근 관절(radiocarpal joint), 중수근 관절',
  false,
  '수근골에 전방 또는 후방 활주를 유지하면서 환자가 손목 운동을 수행하는 Mulligan MWM 기법. 손목 ROM 제한, 요골 골절 후 재활에 적용. YouTube 보충: 신전→요측 활주, 굴곡→척측 활주.',
  '[{"step":1,"instruction":"사전 확인: 손목 ROM 및 통증 방향 기록."},{"step":2,"instruction":"환자 앉은 자세, 전완 테이블 위 지지, 손목 중립."},{"step":3,"instruction":"고정손: 요골·척골 원위부 고정. 활주손: 수근골 근위열에 양 엄지 접촉."},{"step":4,"instruction":"활주 방향 탐색: 전방·후방·척측·요측 순 시도 → 무통 방향 확인."},{"step":5,"instruction":"활주 유지 + 환자 능동 운동. 통증 소실 확인. 10회 × 3세트."}]'::jsonb,
  '앉은 자세, 전완 테이블 위, 손목 중립',
  '환자 전방 또는 측방',
  '고정손: 요골·척골 원위부. 활주손: 수근골 근위열 양 엄지',
  '전방(palmar), 후방(dorsal), 척측(ulnar), 또는 요측(radial) 활주 — 방향 탐색',
  '{"rom_improvement","pain_relief"}',
  '{"post_surgical","subacute","chronic"}',
  '{}',
  '{"instability","fracture","inflammation_acute"}',
  'level_2b'::evidence_level,
  '[{"pmid":"28110866","title":"Wrist MWM clinical applications","year":2017}]'::jsonb,
  '요골 원위부 골절 재활에서 수근골 전방 활주 MWM이 굴곡 ROM 회복에 효과적. YouTube: 신전 제한 → 요측 활주, 굴곡 제한 → 척측 활주. CKC self-MWM: 테이블 모서리에 손 대고 체중 부하.',
  'TFCC 파열 불안정, 급성 골절',
  '급성 염증기',
  true,
  false
);

-- [36/42] 손가락 MWM (tech-B-016)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '손가락 MWM',
  'Finger MWM',
  'Finger MWM',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'wrist_hand'::body_region,
  'MCP·PIP·DIP 관절',
  false,
  '지절 관절에 측방 또는 전방 활주를 유지하면서 환자가 손가락 굴곡·신전을 수행하는 Mulligan MWM 기법. 골절 후 강직, 류마티스 후기 재활에 적용.',
  '[{"step":1,"instruction":"사전 확인: 굴곡/신전 ROM 기록."},{"step":2,"instruction":"환자 앉은 자세, 손 테이블 위 지지."},{"step":3,"instruction":"고정손: 근위 지절 고정. 활주손: 원위 지절에 엄지·검지로 측방 또는 전방 활주."},{"step":4,"instruction":"무통 방향 탐색 후 환자 굴곡/신전 지시."},{"step":5,"instruction":"10회 × 3세트."}]'::jsonb,
  '앉은 자세, 손 테이블 위',
  '환자 측방',
  '고정손: 근위 지절. 활주손: 원위 지절 엄지·검지로 파지',
  '측방(lateral) 또는 전방(palmar) 활주',
  '{"rom_improvement"}',
  '{"post_surgical","subacute","chronic"}',
  '{}',
  '{"fracture","instability","inflammation_acute"}',
  'level_3'::evidence_level,
  '[{"pmid":"28110866","title":"Finger MWM clinical applications","year":2017}]'::jsonb,
  '손가락 관절은 방향 탐색이 중요 — 측방 활주 방향이 굴곡 MWM에서 효과적인 경우 많음. 류마티스 활동기에는 Grade I 수준 활주만 적용.',
  '급성 인대 파열, 급성 골절',
  '류마티스 관절염 활동기',
  true,
  false
);

-- [37/42] 고관절 MWM (tech-B-017)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '고관절 MWM',
  'Hip MWM',
  'Hip MWM',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'hip'::body_region,
  '고관절(hip joint)',
  false,
  '치료 벨트로 대퇴골두에 외측 견인 활주를 유지하면서 환자가 고관절 굴곡·내회전을 수행하는 Mulligan MWM 기법. 고관절 OA, FAI 관련 ROM 제한에 적용. RCT 근거: 굴곡 +12.2°, 내회전 +4.4°.',
  '[{"step":1,"instruction":"사전 기준 동작: 고관절 ROM(굴곡·내회전·외회전) 기록."},{"step":2,"instruction":"환자 누운 자세(supine) 또는 서기 자세. 치료 벨트를 대퇴 근위부에 착용."},{"step":3,"instruction":"치료사 체중으로 벨트를 외측으로 당겨 외측 견인 활주 유지."},{"step":4,"instruction":"환자 능동 운동 지시(고관절 굴곡 또는 내회전). 통증 소실 확인."},{"step":5,"instruction":"10회 × 3세트. Self-MWM: 벨트 이용 자가 외측 견인 + 내회전 교육."}]'::jsonb,
  '누운 자세(supine, 고관절 약 70° 굴곡) 또는 서기 자세',
  '환자 측방, 치료 벨트로 외측 견인',
  '치료 벨트: 대퇴 근위부. 손: 대퇴 근위 내측 또는 외측',
  '외측(lateral) 견인 활주',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic","elderly","athlete"}',
  '{"knee_oa"}',
  '{"fracture","instability","inflammation_acute"}',
  'level_1b'::evidence_level,
  '[{"pmid":"26972719","title":"Hip MWM for OA: RCT (Beselga 2016)","year":2016}]'::jsonb,
  '외측 견인 벨트 MWM이 단독 손 MWM보다 효과적. RCT 결과: 굴곡 ROM +12.2°, 내회전 +4.4°. 중년 고관절 OA + 내회전 제한에서 우선 시도. Self-MWM 가정 연습 교육 강력 권장.',
  '고관절 완전 치환술 후 초기, 급성 골절',
  '급성 활막염, 고관절 불안정',
  true,
  false
);

-- [38/42] 무릎 MWM — 굴곡 (tech-B-018)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '무릎 MWM — 굴곡',
  'Knee MWM Flexion',
  'Knee MWM Flex',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'knee'::body_region,
  '경골대퇴관절(tibiofemoral joint)',
  false,
  '경골 근위부에 내측 활주를 유지하면서 환자가 무릎 굴곡을 수행하는 Mulligan MWM 기법. TKR 재활, OA, ACL 재건 후 굴곡 제한에 적용. 내측 활주 방향이 가장 효과적인 경우 많음.',
  '[{"step":1,"instruction":"사전 기준 동작: 무릎 굴곡 ROM 기록."},{"step":2,"instruction":"환자 앉거나 서기. 치료사 측방. 고정손: 대퇴골 원위부 고정. 활주손: 경골 근위부 내측 활주 준비."},{"step":3,"instruction":"활주 방향 탐색: 내측 활주 → 외측 활주 순 시도."},{"step":4,"instruction":"무통 방향 확인 후 활주 유지 + 환자 굴곡 지시. 통증 소실(VAS 0)."},{"step":5,"instruction":"10회 × 3세트. 비체중부하에서 효과 있으면 서기 자세로 업그레이드."}]'::jsonb,
  '앉은 자세 또는 서기, 무릎 신전에서 시작',
  '환자 측방',
  '고정손: 대퇴골 원위부. 활주손: 경골 근위부(관절선 바로 아래) 내측 또는 외측',
  '내측(medial) 또는 외측(lateral) 활주 — 내측 우선',
  '{"rom_improvement","pain_relief"}',
  '{"post_surgical","subacute","chronic","elderly"}',
  '{"knee_oa","patellofemoral"}',
  '{"instability","fracture","inflammation_acute"}',
  'level_1b'::evidence_level,
  '[{"pmid":"23683686","title":"Knee MWM for flexion ROM: RCT (Takasaki 2013)","year":2013}]'::jsonb,
  'TKR 후 굴곡 제한에서 내측 활주 방향이 가장 효과적. Self-MWM: 치료 테이프로 경골 내측 활주 고정 후 스쿼트. YouTube: 4 세션만으로 유의한 개선. 경골 근위부 관절선 바로 아래 접촉이 최적.',
  '급성 인대 파열, 골절, 심한 불안정성',
  '급성 관절염, 심한 삼출',
  true,
  false
);

-- [39/42] 무릎 MWM — 신전 (tech-B-019)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '무릎 MWM — 신전',
  'Knee MWM Extension',
  'Knee MWM Ext',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'knee'::body_region,
  '경골대퇴관절(tibiofemoral joint)',
  false,
  '경골 근위부에 전방 또는 내측 활주를 유지하면서 환자가 무릎 신전을 수행하는 Mulligan MWM 기법. 무릎 신전 제한, extension lag, TKR 후 신전 회복에 적용.',
  '[{"step":1,"instruction":"사전 확인: 신전 ROM 기록."},{"step":2,"instruction":"환자 앉은 자세, 무릎 약 90° 굴곡에서 시작."},{"step":3,"instruction":"고정손: 대퇴골 원위부 고정. 활주손: 경골 근위부 전방 또는 내측 활주 탐색."},{"step":4,"instruction":"무통 방향 확인 후 활주 유지 + 환자 신전 지시."},{"step":5,"instruction":"10회 × 3세트."}]'::jsonb,
  '앉은 자세, 무릎 90° 굴곡',
  '환자 측방',
  '고정손: 대퇴골 원위부. 활주손: 경골 근위부 전방 또는 내측',
  '전방(anterior) 또는 내측(medial) 활주',
  '{"rom_improvement"}',
  '{"post_surgical","subacute"}',
  '{"knee_oa"}',
  '{"instability","fracture"}',
  'level_3'::evidence_level,
  '[{"pmid":"23683686","title":"Knee MWM techniques","year":2013}]'::jsonb,
  'TKR 후 신전 제한에서 전방 활주 MWM 적용 시 extension lag 조기 해소. 굴곡 MWM과 병행하여 TKR 재활 포괄적 ROM 회복.',
  '급성 골절, PCL 불안정',
  '심한 삼출',
  true,
  false
);

-- [40/42] 경비관절 MWM (tech-B-020)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '경비관절 MWM',
  'Proximal Tibiofibular MWM',
  'TF MWM',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'knee'::body_region,
  '근위 경비관절(proximal tibiofibular joint)',
  false,
  '비골두(fibular head)를 전방 또는 후방으로 활주하면서 환자가 무릎 굴곡 또는 발목 배굴을 수행하는 Mulligan MWM 기법. 무릎 외측 통증, 근위 경비관절 기능부전에 적용.',
  '[{"step":1,"instruction":"사전 확인: 비골두 압통 및 무릎 외측 통증 ROM 확인."},{"step":2,"instruction":"환자 앉은 자세, 무릎 90° 굴곡."},{"step":3,"instruction":"고정손: 경골 근위부 내측 고정. 활주손: 비골두에 엄지 접촉 → 전방 또는 후방 활주 탐색."},{"step":4,"instruction":"무통 방향 확인 후 환자 무릎 굴곡 지시. 10회 × 3세트."}]'::jsonb,
  '앉은 자세, 무릎 90° 굴곡',
  '환자 측방',
  '고정손: 경골 근위부 내측. 활주손: 비골두 엄지 접촉',
  '전방(anterior) 또는 후방(posterior) 활주',
  '{"pain_relief","rom_improvement"}',
  '{"subacute","chronic"}',
  '{}',
  '{"fracture"}',
  'level_3'::evidence_level,
  '[{"pmid":"28110866","title":"Proximal tibiofibular MWM: clinical applications","year":2017}]'::jsonb,
  '무릎 외측 통증에서 LCL·IT band 문제와 감별 후 적용. 발목 외측 염좌 후 근위 경비관절 기능부전과 연관된 경우 고려.',
  '비골 골절',
  '근위 경비관절 불안정',
  true,
  false
);

-- [41/42] 발목 MWM 배굴 (체중부하) (tech-B-021)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '발목 MWM 배굴 (체중부하)',
  'Ankle MWM Dorsiflexion Weight-Bearing',
  'Ankle WB MWM',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'ankle_foot'::body_region,
  '거퇴관절(talocrural joint)',
  false,
  '치료 벨트로 거골에 후방 활주를 유지하면서 환자가 서기 자세에서 발목 배굴(런지 동작)을 수행하는 Mulligan WB MWM 기법. 발목 염좌 후 배굴 제한, 스포츠 복귀에 가장 기능적인 기법.',
  '[{"step":1,"instruction":"사전 기준 동작: Knee-to-wall lunge test 거리 기록."},{"step":2,"instruction":"환자 서기 자세. 치료 벨트를 발목 전방(경거 관절 바로 위 거골)에 위치. 치료사 후방으로 벨트 당김."},{"step":3,"instruction":"벨트를 후방으로 당겨 거골 후방 활주 유지."},{"step":4,"instruction":"환자 런지 지시: ''발뒤꿈치를 바닥에서 떼지 말고 무릎을 앞으로 밀어보세요''."},{"step":5,"instruction":"통증 소실 확인(VAS 0). 10회 × 3세트. Knee-to-wall 재측정. Self-MWM 타월 교육."}]'::jsonb,
  '서기 자세(weight-bearing), 시술 측 발을 스텝 또는 바닥에서 런지',
  '환자 전방 또는 측방, 무릎 굴곡 낮은 자세',
  '치료 벨트: 발목 전방 거골(경거 관절 바로 위). 고정손: 발뒤꿈치 지지',
  '거골 후방(posterior) 활주',
  '{"rom_improvement","pain_relief"}',
  '{"subacute","chronic","athlete","post_surgical"}',
  '{"ankle_sprain"}',
  '{"fracture","instability","inflammation_acute"}',
  'level_1b'::evidence_level,
  '[{"pmid":"16717267","title":"WB ankle MWM for dorsiflexion ROM: RCT (Vicenzino 2006)","year":2006},{"pmid":"24726360","title":"Ankle MWM for chronic ankle instability (Loudon 2014)","year":2014}]'::jsonb,
  '가장 기능적인 Mulligan 발목 기법. YouTube 보충: 후방 거골 활주 55% 즉각 개선, WB 배굴 26% 개선. Self-MWM: 타월 이용 자가 후방 활주 + 런지 — 매우 효과적인 HEP. 스포츠 복귀 평가에 lunge test 활용. Dosage: 10회 × 5세트 × 5일/주 × 4주.',
  '급성 발목 골절, Grade III 인대 파열',
  '심한 급성 부종·혈종',
  true,
  false
);

-- [42/42] 발가락 MTP MWM (tech-B-022)
INSERT INTO techniques (
  name_ko,
  name_en,
  abbreviation,
  category,
  subcategory,
  body_region,
  body_segment,
  is_bilateral,
  description,
  technique_steps,
  patient_position,
  therapist_position,
  contact_point,
  direction,
  purpose_tags,
  target_tags,
  symptom_tags,
  contraindication_tags,
  evidence_level,
  key_references,
  clinical_notes,
  absolute_contraindications,
  relative_contraindications,
  is_active,
  is_published
) VALUES (
  '발가락 MTP MWM',
  'Metatarsophalangeal Joint MWM',
  'MTP MWM',
  'category_b_mulligan'::technique_category,
  'Mulligan',
  'ankle_foot'::body_region,
  '중족지절 관절(MTP joint) — 주로 1st MTP',
  false,
  '1st MTP 관절의 근위 지절에 배측 또는 측방 활주를 유지하면서 환자가 엄지발가락 신전을 수행하는 Mulligan MWM 기법. Hallux rigidus/limitus, 보행 push-off 통증에 적용.',
  '[{"step":1,"instruction":"사전 확인: MTP 신전 ROM 기록, 보행 시 push-off 통증 확인."},{"step":2,"instruction":"환자 앉거나 서기. 고정손: 1번 중족골 원위부 고정. 활주손: 근위 지절에 엄지·검지로 배측 또는 측방 활주."},{"step":3,"instruction":"활주 방향 탐색: 배측 → 측방 → 배측+측방 순."},{"step":4,"instruction":"무통 방향 확인 후 환자 엄지발가락 신전 지시. 통증 소실 확인."},{"step":5,"instruction":"10회 × 3세트. 서기 발끝서기로 업그레이드."}]'::jsonb,
  '앉거나 서기',
  '환자 발 측방',
  '고정손: 1번 중족골 원위부. 활주손: 근위 지절 엄지·검지 파지',
  '배측(dorsal) 또는 측방(lateral) 활주',
  '{"pain_relief","rom_improvement"}',
  '{"chronic","elderly","subacute"}',
  '{}',
  '{"fracture","inflammation_acute"}',
  'level_3'::evidence_level,
  '[{"pmid":"28110866","title":"MTP MWM clinical applications: Mulligan concept","year":2017}]'::jsonb,
  'Hallux valgus 관련 내측 통증 시 내측 활주 시도. 급성 통풍 발작 중 금기. 서기 발끝서기 업그레이드 시 보행 push-off 동작 훈련 연계.',
  '급성 통풍 발작, 중족골 골절',
  '급성 염증기',
  true,
  false
);

-- ============================================================
-- technique_stats 초기 레코드 생성 (모든 테크닉에 대해)
-- recommendation_weight 초기값 0.7
-- ============================================================
INSERT INTO technique_stats (technique_id, recommendation_weight)
SELECT id, 0.7 FROM techniques
ON CONFLICT (technique_id) DO NOTHING;

-- ============================================================
-- END OF SEED
-- ============================================================
